<?php

// Connection details come from the environment so no credentials live in the
// repo. Defaults target the local XAMPP database.
$conn = mysqli_init();
$conn->real_connect(
    getenv('DB_HOST') ?: 'localhost',
    getenv('DB_USER') ?: 'root',
    getenv('DB_PASS') ?: '',
    getenv('DB_NAME') ?: 'b2btradeservices',
    (int) (getenv('DB_PORT') ?: 3306),
);

if ($conn->connect_error) {
    die('Connection failed: ' . $conn->connect_error);
}
echo "Connected to database.\n";

$maxIdRow = $conn->query("SELECT MAX(id) as mx FROM users")->fetch_assoc();
$startUserId = ($maxIdRow['mx'] ?? 0) + 1;

$maxProdRow = $conn->query("SELECT MAX(id) as mx FROM products")->fetch_assoc();
$startProdId = ($maxProdRow['mx'] ?? 0) + 1;

$maxUidRow = $conn->query("SELECT uid FROM users WHERE uid LIKE 'SUP-%' ORDER BY uid DESC LIMIT 1")->fetch_assoc();
$uidStart = $maxUidRow ? ((int)str_replace('SUP-', '', $maxUidRow['uid'])) + 1 : 1;

$suppliers = [
    ['name'=>'Ahmed Al Rashid','company_name'=>'Gulf Steel Industries LLC','email'=>'ahmed@gulfsteel.ae','phone'=>'+971501234567','phone_code'=>'+971','country_id'=>1,'city'=>'Dubai','website'=>'https://www.gulfsteelindustries.ae','selling_products'=>'Steel Pipes, Steel Beams, Reinforcement Bars, Steel Coils','membership_level'=>'gold','lead_stage'=>'connected_talking','whatsapp'=>1,'logo'=>'supplier_logo_1_1.jpg'],
    ['name'=>'Muhammad Hassan','company_name'=>'PakTex Mills Pvt Ltd','email'=>'hassan@paktexmills.pk','phone'=>'+923001234567','phone_code'=>'+92','country_id'=>2,'city'=>'Faisalabad','website'=>'https://www.paktexmills.com','selling_products'=>'Cotton Fabric, Denim, Terry Towels, Bed Linen','membership_level'=>'platinum','lead_stage'=>'services_pitched','whatsapp'=>1,'logo'=>'supplier_logo_1_2.jpg'],
    ['name'=>'Rajesh Kumar','company_name'=>'IndoChem Solutions Pvt Ltd','email'=>'rajesh@indochem.in','phone'=>'+919876543210','phone_code'=>'+91','country_id'=>3,'city'=>'Mumbai','website'=>'https://www.indochemsolutions.com','selling_products'=>'Industrial Chemicals, Solvents, Adhesives, Coating Materials','membership_level'=>'silver','lead_stage'=>'new','whatsapp'=>1,'logo'=>'supplier_logo_1_3.jpg'],
    ['name'=>'Li Wei','company_name'=>'Shenzhen TechPro Electronics Co','email'=>'liwei@techpro.cn','phone'=>'+8613800138000','phone_code'=>'+86','country_id'=>4,'city'=>'Shenzhen','website'=>'https://www.techpro-electronics.cn','selling_products'=>'LED Displays, Circuit Boards, Electronic Components, Smart Devices','membership_level'=>'vip','lead_stage'=>'contract_sent','whatsapp'=>0,'logo'=>'supplier_logo_1_4.jpg'],
    ['name'=>'Fatima Rahman','company_name'=>'Dhaka Garments International','email'=>'fatima@dhakagarments.bd','phone'=>'+8801712345678','phone_code'=>'+880','country_id'=>5,'city'=>'Dhaka','website'=>'https://www.dhakagarments.com','selling_products'=>'Ready-Made Garments, Knitwear, Woven Shirts, Denim Jeans','membership_level'=>'gold','lead_stage'=>'interested_premium','whatsapp'=>1,'logo'=>'supplier_logo_1_5.jpg'],
    ['name'=>'Mehmet Yilmaz','company_name'=>'Istanbul Marble & Stone Trading','email'=>'mehmet@istanbulmarble.tr','phone'=>'+905551234567','phone_code'=>'+90','country_id'=>9,'city'=>'Istanbul','website'=>'https://www.istanbulmarble.com.tr','selling_products'=>'Marble Slabs, Granite Tiles, Travertine, Natural Stone','membership_level'=>'silver','lead_stage'=>'trying_to_connect','whatsapp'=>1,'logo'=>'supplier_logo_1_6.jpg'],
    ['name'=>'Khalid Al Saud','company_name'=>'Arabian Petrochemicals Corp','email'=>'khalid@arabpetro.sa','phone'=>'+966501234567','phone_code'=>'+966','country_id'=>10,'city'=>'Riyadh','website'=>'https://www.arabianpetrochem.com','selling_products'=>'Polyethylene, Polypropylene, PVC Resin, Industrial Lubricants','membership_level'=>'platinum','lead_stage'=>'connected_talking','whatsapp'=>1,'logo'=>'supplier_logo_1_7.jpg'],
    ['name'=>'Nguyen Van Tran','company_name'=>'Vietnam AgriExport Joint Stock Co','email'=>'tran@vnagriexport.vn','phone'=>'+84912345678','phone_code'=>'+84','country_id'=>13,'city'=>'Ho Chi Minh City','website'=>'https://www.vnagriexport.com','selling_products'=>'Rice, Coffee Beans, Cashew Nuts, Black Pepper, Spices','membership_level'=>'gold','lead_stage'=>'services_pitched','whatsapp'=>1,'logo'=>'supplier_logo_1_8.jpg'],
    ['name'=>'Hans Mueller','company_name'=>'Deutsche MaschinenTech GmbH','email'=>'mueller@maschinentech.de','phone'=>'+4915112345678','phone_code'=>'+49','country_id'=>17,'city'=>'Stuttgart','website'=>'https://www.maschinentech.de','selling_products'=>'CNC Machines, Hydraulic Presses, Injection Molding, Packaging Machines','membership_level'=>'vip','lead_stage'=>'contract_sent','whatsapp'=>0,'logo'=>'supplier_logo_1_9.jpg'],
    ['name'=>'James Wilson','company_name'=>'American MedTech Supplies Inc','email'=>'james@ammedtech.com','phone'=>'+12025551234','phone_code'=>'+1','country_id'=>19,'city'=>'Chicago','website'=>'https://www.ammedtech.com','selling_products'=>'Surgical Instruments, Diagnostic Equipment, PPE, Lab Supplies','membership_level'=>'platinum','lead_stage'=>'interested_premium','whatsapp'=>0,'logo'=>'supplier_logo_1_10.jpg'],
    ['name'=>'Chen Xiao Ming','company_name'=>'Guangzhou Home Furnishing Co Ltd','email'=>'chen@gzhomefurnish.cn','phone'=>'+8613600136000','phone_code'=>'+86','country_id'=>4,'city'=>'Guangzhou','website'=>'https://www.gzhomefurnishing.com','selling_products'=>'Sofas, Dining Tables, Office Furniture, Outdoor Furniture','membership_level'=>'gold','lead_stage'=>'connected_talking','whatsapp'=>1,'logo'=>'supplier_logo_2_1.jpg'],
    ['name'=>'Anwar Ibrahim','company_name'=>'MalayTech Components Sdn Bhd','email'=>'anwar@malaytech.my','phone'=>'+60121234567','phone_code'=>'+60','country_id'=>11,'city'=>'Kuala Lumpur','website'=>'https://www.malaytech.com.my','selling_products'=>'Semiconductors, PCB Boards, Connectors, Sensors','membership_level'=>'silver','lead_stage'=>'new','whatsapp'=>1,'logo'=>'supplier_logo_2_2.jpg'],
    ['name'=>'Priya Sharma','company_name'=>'Jaipur Handicrafts Export House','email'=>'priya@jaipurhandicraft.in','phone'=>'+919812345678','phone_code'=>'+91','country_id'=>3,'city'=>'Jaipur','website'=>'https://www.jaipurhandicrafts.com','selling_products'=>'Handmade Rugs, Brass Decor, Wooden Furniture, Marble Artifacts','membership_level'=>'free','lead_stage'=>'new','whatsapp'=>1,'logo'=>'supplier_logo_2_3.jpg'],
    ['name'=>'John Smith','company_name'=>'UK AutoParts Distribution Ltd','email'=>'john@ukautodist.co.uk','phone'=>'+447911123456','phone_code'=>'+44','country_id'=>18,'city'=>'Birmingham','website'=>'https://www.ukautoparts.co.uk','selling_products'=>'Brake Pads, Engine Parts, Suspension Systems, Car Batteries','membership_level'=>'gold','lead_stage'=>'services_pitched','whatsapp'=>0,'logo'=>'supplier_logo_2_4.jpg'],
    ['name'=>'Yuki Tanaka','company_name'=>'Osaka Precision Instruments Co','email'=>'tanaka@osakapi.jp','phone'=>'+81901234567','phone_code'=>'+81','country_id'=>16,'city'=>'Osaka','website'=>'https://www.osakaprecision.jp','selling_products'=>'Measuring Tools, Optical Instruments, Lab Equipment, Testing Machines','membership_level'=>'platinum','lead_stage'=>'contract_sent','whatsapp'=>0,'logo'=>'supplier_logo_2_5.jpg'],
    ['name'=>'Omar Farouk','company_name'=>'Cairo Building Materials Co','email'=>'omar@cairobuild.eg','phone'=>'+201001234567','phone_code'=>'+20','country_id'=>20,'city'=>'Cairo','website'=>'https://www.cairobuildingmaterials.com','selling_products'=>'Cement, Ceramic Tiles, Sanitary Ware, Paint Products','membership_level'=>'silver','lead_stage'=>'trying_to_connect','whatsapp'=>1,'logo'=>'supplier_logo_2_6.jpg'],
    ['name'=>'Kim Soo Jin','company_name'=>'Seoul Sports Equipment Co Ltd','email'=>'kim@seoulsports.kr','phone'=>'+821012345678','phone_code'=>'+82','country_id'=>15,'city'=>'Seoul','website'=>'https://www.seoulsports.co.kr','selling_products'=>'Fitness Equipment, Sports Wear, Yoga Mats, Resistance Bands','membership_level'=>'gold','lead_stage'=>'interested_premium','whatsapp'=>0,'logo'=>'supplier_logo_2_7.jpg'],
    ['name'=>'Roberto Santos','company_name'=>'Brasil PackPrint Industria Ltda','email'=>'roberto@brasilpackprint.br','phone'=>'+5511987654321','phone_code'=>'+55','country_id'=>30,'city'=>'Sao Paulo','website'=>'https://www.brasilpackprint.com.br','selling_products'=>'Corrugated Boxes, Flexible Packaging, Labels, Printing Services','membership_level'=>'silver','lead_stage'=>'new','whatsapp'=>1,'logo'=>'supplier_logo_2_8.jpg'],
    ['name'=>'Suresh Patel','company_name'=>'Gujarat Pharma Industries','email'=>'suresh@gujaratpharma.in','phone'=>'+919998887776','phone_code'=>'+91','country_id'=>3,'city'=>'Ahmedabad','website'=>'https://www.gujaratpharma.com','selling_products'=>'Generic Medicines, API Ingredients, Nutraceuticals, Ayurvedic Products','membership_level'=>'free','lead_stage'=>'trying_to_connect','whatsapp'=>1,'logo'=>'supplier_logo_2_9.jpg'],
    ['name'=>'Ali Hassan','company_name'=>'Bahrain Metal Works WLL','email'=>'ali@bahrainmetal.bh','phone'=>'+97339876543','phone_code'=>'+973','country_id'=>27,'city'=>'Manama','website'=>'https://www.bahrainmetalworks.com','selling_products'=>'Aluminum Profiles, Steel Fabrication, Metal Gates, Railings','membership_level'=>'gold','lead_stage'=>'connected_talking','whatsapp'=>1,'logo'=>'supplier_logo_2_10.jpg'],
];

echo "Inserting 20 suppliers...\n";
$supplierIds = [];
$supplierUidCounter = $uidStart;

foreach ($suppliers as $i => $s) {
    $uid = 'SUP-' . str_pad($supplierUidCounter, 6, '0', STR_PAD_LEFT);
    $supplierUidCounter++;
    $hashedPass = password_hash('supplier123', PASSWORD_DEFAULT);
    $now = date('Y-m-d H:i:s', strtotime('-' . rand(1, 90) . ' days'));

    $stmt = $conn->prepare("INSERT INTO users (uid, name, email, password, phone, phone_code, whatsapp, country_id, user_type, selling_products, company_name, website, city, membership_level, lead_stage, lead_source, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'supplier', ?, ?, ?, ?, ?, ?, 'website', 'approved', ?, ?)");
    $stmt->bind_param('ssssssiissssssss',
        $uid, $s['name'], $s['email'], $hashedPass, $s['phone'], $s['phone_code'],
        $s['whatsapp'], $s['country_id'], $s['selling_products'], $s['company_name'],
        $s['website'], $s['city'], $s['membership_level'], $s['lead_stage'], $now, $now
    );

    if ($stmt->execute()) {
        $newId = $conn->insert_id;
        $supplierIds[] = $newId;
        echo "  Inserted supplier #{$newId}: {$s['company_name']} ({$uid})\n";

        $logoFile = $s['logo'];
        $conn->query("UPDATE users SET company_logo='" . $conn->real_escape_string($logoFile) . "' WHERE id={$newId}");
    } else {
        echo "  ERROR inserting supplier {$s['company_name']}: " . $stmt->error . "\n";
        $supplierIds[] = null;
    }
    $stmt->close();
}

$products = [
    ['cat'=>1,'supplier_idx'=>0,'name'=>'Premium Reinforced Steel Bars','slug'=>'premium-reinforced-steel-bars','desc'=>'High-quality reinforced steel bars for construction projects. Available in various diameters from 8mm to 32mm. Meets international ASTM A615 standards for structural applications.','specs'=>'Diameter: 8-32mm|Grade: Grade 60|Length: 6m, 9m, 12m|Standard: ASTM A615','moq'=>500,'unit'=>'Tons','price'=>'$450 - $550 / Ton','supply'=>'5000 Tons per Month','delivery'=>'15-20 days','packaging'=>'Bundled with steel straps','port'=>'Jebel Ali Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, ASTM Certified','img'=>'product_build_1_1.jpg','featured'=>1],
    ['cat'=>1,'supplier_idx'=>5,'name'=>'Italian White Marble Slabs','slug'=>'italian-white-marble-slabs','desc'=>'Premium quality Italian white marble slabs sourced from the finest quarries in Turkey. Perfect for luxury interior and exterior applications including flooring, wall cladding, and countertops.','specs'=>'Thickness: 15-30mm|Size: 240x120cm|Finish: Polished, Honed|Color: White with grey veining','moq'=>50,'unit'=>'Slabs','price'=>'$80 - $150 / Square Meter','supply'=>'2000 Square Meters per Month','delivery'=>'20-30 days','packaging'=>'Wooden crates with foam protection','port'=>'Mersin Port','payment'=>'T/T, L/C','certs'=>'CE Certified, ISO 9001','img'=>'product_build_1_2.jpg','featured'=>1],
    ['cat'=>1,'supplier_idx'=>15,'name'=>'Portland Cement OPC 42.5N','slug'=>'portland-cement-opc','desc'=>'Ordinary Portland Cement Grade 42.5N. Ideal for all types of construction work including foundations, pillars, beams, and slabs. Consistent quality with high early strength.','specs'=>'Grade: 42.5N|Type: OPC|Setting Time: Initial 45min|Packaging: 50kg bags','moq'=>1000,'unit'=>'Bags','price'=>'$4.50 - $5.50 / Bag','supply'=>'50000 Bags per Month','delivery'=>'7-14 days','packaging'=>'50kg woven bags on pallets','port'=>'Alexandria Port','payment'=>'T/T, L/C','certs'=>'EN 197-1, ISO 9001','img'=>'product_build_1_3.jpg','featured'=>0],
    ['cat'=>1,'supplier_idx'=>15,'name'=>'Porcelain Floor Tiles 60x60cm','slug'=>'porcelain-floor-tiles-60x60','desc'=>'High-quality glazed porcelain floor tiles with wood-grain finish. Suitable for residential and commercial spaces. Scratch-resistant and easy to maintain.','specs'=>'Size: 60x60cm|Thickness: 9.5mm|Finish: Matte, Glossy|Water Absorption: <0.5%','moq'=>200,'unit'=>'Square Meters','price'=>'$8 - $15 / Square Meter','supply'=>'10000 Square Meters per Month','delivery'=>'10-15 days','packaging'=>'Carton boxes on pallets','port'=>'Alexandria Port','payment'=>'T/T, L/C','certs'=>'ISO 13006, CE Mark','img'=>'product_build_1_4.jpg','featured'=>0],
    ['cat'=>1,'supplier_idx'=>0,'name'=>'Galvanized Steel Pipes','slug'=>'galvanized-steel-pipes','desc'=>'Hot-dip galvanized steel pipes for plumbing, scaffolding, and structural applications. Zinc-coated for superior corrosion resistance. Available in round and square profiles.','specs'=>'Diameter: 1/2" to 8"|Wall Thickness: 1.5-6mm|Length: 6m|Coating: Hot-dip Galvanized','moq'=>100,'unit'=>'Tons','price'=>'$600 - $800 / Ton','supply'=>'3000 Tons per Month','delivery'=>'10-15 days','packaging'=>'Bundled with plastic caps','port'=>'Jebel Ali Port','payment'=>'T/T, L/C','certs'=>'ASTM A53, ISO 9001','img'=>'product_build_1_5.jpg','featured'=>0],
    ['cat'=>1,'supplier_idx'=>5,'name'=>'Granite Kitchen Countertops','slug'=>'granite-kitchen-countertops','desc'=>'Premium natural granite countertops in various colors and patterns. Custom cut to order with polished edges. Perfect for kitchen islands, bathroom vanities, and commercial spaces.','specs'=>'Thickness: 20mm, 30mm|Colors: Black Galaxy, Kashmir White|Edge: Bullnose, Bevel|Finish: Polished','moq'=>20,'unit'=>'Pieces','price'=>'$50 - $120 / Square Meter','supply'=>'500 Square Meters per Month','delivery'=>'15-25 days','packaging'=>'Wooden crate with foam','port'=>'Mersin Port','payment'=>'T/T, L/C','certs'=>'CE Certified','img'=>'product_build_1_6.jpg','featured'=>0],
    ['cat'=>1,'supplier_idx'=>19,'name'=>'Aluminum Window Profiles','slug'=>'aluminum-window-profiles','desc'=>'Extruded aluminum profiles for windows and doors. Thermal break technology for superior insulation. Available in silver, bronze, and custom powder-coated colors.','specs'=>'Alloy: 6063-T5|Wall Thickness: 1.4mm|Finish: Anodized, Powder Coated|System: Sliding, Casement','moq'=>500,'unit'=>'Meters','price'=>'$3 - $8 / Meter','supply'=>'20000 Meters per Month','delivery'=>'15-20 days','packaging'=>'Protective film and shrink wrap','port'=>'Khalifa Bin Salman Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, QUALICOAT','img'=>'product_build_1_7.jpg','featured'=>0],
    ['cat'=>1,'supplier_idx'=>19,'name'=>'Stainless Steel Railings','slug'=>'stainless-steel-railings','desc'=>'Modern stainless steel railing systems for balconies, staircases, and terraces. Made from premium grade 304 stainless steel with mirror or satin finish.','specs'=>'Grade: SS 304|Pipe Diameter: 50mm|Height: 900-1100mm|Finish: Mirror, Satin','moq'=>50,'unit'=>'Meters','price'=>'$35 - $65 / Meter','supply'=>'2000 Meters per Month','delivery'=>'10-15 days','packaging'=>'Bubble wrap in carton boxes','port'=>'Khalifa Bin Salman Port','payment'=>'T/T','certs'=>'ISO 9001','img'=>'product_build_1_8.jpg','featured'=>0],

    ['cat'=>2,'supplier_idx'=>7,'name'=>'Premium Jasmine Rice 5% Broken','slug'=>'premium-jasmine-rice-5-broken','desc'=>'Vietnamese premium long-grain jasmine rice with distinctive aroma. Ideal for wholesale and retail distribution. Carefully milled and sorted for consistent quality.','specs'=>'Broken: 5% Max|Moisture: 14% Max|Length: 6.8mm+|Crop Year: 2025','moq'=>25,'unit'=>'Tons','price'=>'$480 - $550 / Ton','supply'=>'5000 Tons per Month','delivery'=>'14-21 days','packaging'=>'25kg, 50kg PP bags or custom','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'ISO 22000, HACCP, Phytosanitary','img'=>'product_agri_1_1.jpg','featured'=>1],
    ['cat'=>2,'supplier_idx'=>7,'name'=>'Robusta Coffee Beans Grade 1','slug'=>'robusta-coffee-beans-grade1','desc'=>'High-quality Vietnamese Robusta coffee beans, screen 18. Double-sorted for minimal defects. Strong flavor profile ideal for espresso blends and instant coffee manufacturing.','specs'=>'Screen: 18|Moisture: 12.5% Max|Defect: 1% Max|Polished: Yes','moq'=>20,'unit'=>'Tons','price'=>'$2200 - $2800 / Ton','supply'=>'500 Tons per Month','delivery'=>'14-21 days','packaging'=>'60kg jute bags or bulk','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'ISO 22000, UTZ, Fair Trade','img'=>'product_agri_1_2.jpg','featured'=>1],
    ['cat'=>2,'supplier_idx'=>7,'name'=>'Raw Cashew Nuts W320','slug'=>'raw-cashew-nuts-w320','desc'=>'Premium whole cashew nuts grade W320. Clean white color with consistent size. Perfect for snacking, confectionery, and food manufacturing.','specs'=>'Grade: W320|Moisture: 5% Max|Color: White/Ivory|Packaging: Vacuum sealed','moq'=>5,'unit'=>'Tons','price'=>'$7500 - $9000 / Ton','supply'=>'200 Tons per Month','delivery'=>'14-21 days','packaging'=>'Tin cans in carton boxes','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'HACCP, BRC, FDA','img'=>'product_agri_1_3.jpg','featured'=>0],
    ['cat'=>2,'supplier_idx'=>7,'name'=>'Black Pepper Whole Grade FAQ','slug'=>'black-pepper-whole-faq','desc'=>'Vietnamese black pepper, bold and aromatic. Sun-dried whole peppercorns suitable for grinding, food processing, and spice trading. Consistent pungency and flavor.','specs'=>'Moisture: 13% Max|Admixture: 1% Max|Density: 550 g/L Min|Origin: Central Highlands','moq'=>10,'unit'=>'Tons','price'=>'$3800 - $4500 / Ton','supply'=>'300 Tons per Month','delivery'=>'10-14 days','packaging'=>'25kg PP bags, bulk bags','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'ASTA, ISO 22000','img'=>'product_agri_1_4.jpg','featured'=>0],

    ['cat'=>3,'supplier_idx'=>1,'name'=>'100% Cotton Combed Yarn 30s','slug'=>'cotton-combed-yarn-30s','desc'=>'Premium quality 100% cotton combed yarn ideal for knitting and weaving. Excellent uniformity and strength. Available in raw white and bleached white.','specs'=>'Count: 30s|Composition: 100% Cotton|Type: Combed Ring Spun|Strength: 18+ CN/Tex','moq'=>10,'unit'=>'Tons','price'=>'$2.80 - $3.20 / KG','supply'=>'200 Tons per Month','delivery'=>'21-30 days','packaging'=>'Cone packing in cartons','port'=>'Karachi Port','payment'=>'T/T, L/C','certs'=>'OEKO-TEX, ISO 9001','img'=>'product_textile_1_1.jpg','featured'=>1],
    ['cat'=>3,'supplier_idx'=>1,'name'=>'Cotton Terry Bath Towels','slug'=>'cotton-terry-bath-towels','desc'=>'Luxurious 100% cotton terry bath towels. Highly absorbent with excellent softness. Available in various sizes and 48 colors. Custom embroidery and packaging available.','specs'=>'Weight: 500-700 GSM|Size: 70x140cm|Material: 100% Cotton|Colors: 48 options','moq'=>3000,'unit'=>'Pieces','price'=>'$3.50 - $6.00 / Piece','supply'=>'50000 Pieces per Month','delivery'=>'30-45 days','packaging'=>'Individual poly bag, master carton','port'=>'Karachi Port','payment'=>'T/T, L/C','certs'=>'OEKO-TEX, GOTS','img'=>'product_textile_1_2.jpg','featured'=>0],
    ['cat'=>3,'supplier_idx'=>4,'name'=>'Mens Slim Fit Denim Jeans','slug'=>'mens-slim-fit-denim-jeans','desc'=>'High-quality men\'s slim fit denim jeans. Made from premium stretch denim fabric with modern washes. Available in various sizes and wash colors. OEM/ODM orders welcome.','specs'=>'Fabric: 98% Cotton 2% Spandex|Weight: 10-12 oz|Fit: Slim|Sizes: 28-42','moq'=>1000,'unit'=>'Pieces','price'=>'$8 - $14 / Piece','supply'=>'30000 Pieces per Month','delivery'=>'45-60 days','packaging'=>'Folded in poly bags, 20pcs/carton','port'=>'Chittagong Port','payment'=>'T/T, L/C','certs'=>'BSCI, SEDEX, OEKO-TEX','img'=>'product_textile_1_3.jpg','featured'=>1],
    ['cat'=>3,'supplier_idx'=>4,'name'=>'Ladies Cotton T-Shirts','slug'=>'ladies-cotton-t-shirts','desc'=>'Premium quality ladies\' cotton t-shirts in various styles including round neck, V-neck, and polo. Reactive dyed colors that are wash-fast. Custom printing and embroidery available.','specs'=>'Fabric: 100% Cotton Single Jersey|Weight: 160-180 GSM|Sizes: XS-XXL|Styles: Round, V-neck, Polo','moq'=>2000,'unit'=>'Pieces','price'=>'$2.50 - $5.00 / Piece','supply'=>'50000 Pieces per Month','delivery'=>'30-45 days','packaging'=>'Poly bag, 24pcs/carton','port'=>'Chittagong Port','payment'=>'T/T, L/C','certs'=>'BSCI, WRAP, OEKO-TEX','img'=>'product_textile_1_4.jpg','featured'=>0],
    ['cat'=>3,'supplier_idx'=>1,'name'=>'Egyptian Cotton Bed Sheet Set','slug'=>'egyptian-cotton-bed-sheet-set','desc'=>'Luxurious 400 thread count Egyptian cotton bed sheet set. Includes flat sheet, fitted sheet, and two pillowcases. Silky smooth finish with deep pockets for extra-deep mattresses.','specs'=>'Thread Count: 400TC|Material: 100% Egyptian Cotton|Sizes: Twin to California King|Colors: 24 options','moq'=>500,'unit'=>'Sets','price'=>'$18 - $35 / Set','supply'=>'10000 Sets per Month','delivery'=>'30-45 days','packaging'=>'PVC bag with insert card','port'=>'Karachi Port','payment'=>'T/T, L/C','certs'=>'OEKO-TEX, GOTS Organic','img'=>'product_textile_1_5.jpg','featured'=>0],
    ['cat'=>3,'supplier_idx'=>4,'name'=>'Woven Plaid Flannel Shirts','slug'=>'woven-plaid-flannel-shirts','desc'=>'Men\'s premium brushed flannel plaid shirts. Double-brushed for exceptional softness. Available in classic and modern plaid patterns with button-down collar.','specs'=>'Fabric: Cotton Flannel|Weight: 180-200 GSM|Sizes: S-3XL|Patterns: 30+ plaids','moq'=>1500,'unit'=>'Pieces','price'=>'$6 - $10 / Piece','supply'=>'20000 Pieces per Month','delivery'=>'45-60 days','packaging'=>'Folded in poly bags','port'=>'Chittagong Port','payment'=>'T/T, L/C','certs'=>'SEDEX, OEKO-TEX','img'=>'product_textile_1_6.jpg','featured'=>0],

    ['cat'=>4,'supplier_idx'=>3,'name'=>'Indoor P2.5 LED Display Panel','slug'=>'indoor-p25-led-display-panel','desc'=>'Ultra-high resolution indoor LED display panel with 2.5mm pixel pitch. Perfect for shopping malls, airports, conference rooms, and advertising. Seamless splicing for any size.','specs'=>'Pixel Pitch: 2.5mm|Resolution: 160x160 pixels/panel|Brightness: 800-1200 nits|Refresh Rate: 3840Hz','moq'=>10,'unit'=>'Square Meters','price'=>'$350 - $550 / Square Meter','supply'=>'5000 Square Meters per Month','delivery'=>'7-14 days','packaging'=>'Flight case or wooden crate','port'=>'Shenzhen Port','payment'=>'T/T, L/C, PayPal','certs'=>'CE, FCC, RoHS, UL','img'=>'product_elec_1_1.jpg','featured'=>1],
    ['cat'=>4,'supplier_idx'=>3,'name'=>'Smart WiFi Security Camera 4K','slug'=>'smart-wifi-security-camera-4k','desc'=>'Advanced 4K WiFi security camera with AI human detection, night vision, and two-way audio. Easy setup with mobile app. Cloud and SD card storage options. IP66 waterproof.','specs'=>'Resolution: 4K 8MP|Night Vision: 30m IR|Storage: Cloud + 256GB SD|Rating: IP66 Waterproof','moq'=>500,'unit'=>'Pieces','price'=>'$28 - $45 / Piece','supply'=>'50000 Pieces per Month','delivery'=>'7-10 days','packaging'=>'Color box, 20pcs/master carton','port'=>'Shenzhen Port','payment'=>'T/T, PayPal','certs'=>'CE, FCC, RoHS','img'=>'product_elec_1_2.jpg','featured'=>1],
    ['cat'=>4,'supplier_idx'=>11,'name'=>'FR4 PCB Prototype Board','slug'=>'fr4-pcb-prototype-board','desc'=>'Custom FR4 PCB prototype manufacturing service. Multi-layer PCB from 1 to 16 layers. Quick turnaround with high precision. SMT assembly services available.','specs'=>'Layers: 1-16|Material: FR4|Min Trace: 3mil|Surface: HASL, ENIG, OSP','moq'=>5,'unit'=>'Square Meters','price'=>'$1 - $15 / Square Meter','supply'=>'10000 Square Meters per Month','delivery'=>'3-7 days','packaging'=>'Vacuum sealed anti-static bags','port'=>'Port Klang','payment'=>'T/T, PayPal','certs'=>'ISO 9001, UL, IPC-A-600','img'=>'product_elec_1_3.jpg','featured'=>0],
    ['cat'=>4,'supplier_idx'=>3,'name'=>'USB-C Fast Charging Cable 100W','slug'=>'usb-c-fast-charging-cable-100w','desc'=>'Premium USB-C to USB-C fast charging cable supporting 100W PD charging. Nylon braided for durability. Compatible with laptops, tablets, and smartphones. 1m and 2m lengths.','specs'=>'Power: 100W PD|Data: USB 3.1 10Gbps|Length: 1m, 2m|Material: Nylon Braided','moq'=>1000,'unit'=>'Pieces','price'=>'$1.20 - $2.50 / Piece','supply'=>'200000 Pieces per Month','delivery'=>'5-7 days','packaging'=>'Individual box, 100pcs/master carton','port'=>'Shenzhen Port','payment'=>'T/T, PayPal','certs'=>'MFi, USB-IF, CE, RoHS','img'=>'product_elec_1_4.jpg','featured'=>0],
    ['cat'=>4,'supplier_idx'=>11,'name'=>'Industrial Temperature Sensor','slug'=>'industrial-temperature-sensor','desc'=>'High-precision industrial temperature sensor with PT100 RTD element. Stainless steel probe for harsh environments. Accuracy ±0.1°C. Wide temperature range.','specs'=>'Type: PT100 RTD|Range: -200°C to 600°C|Accuracy: ±0.1°C|Probe: SS316','moq'=>100,'unit'=>'Pieces','price'=>'$5 - $25 / Piece','supply'=>'50000 Pieces per Month','delivery'=>'7-10 days','packaging'=>'Individual box, foam protection','port'=>'Port Klang','payment'=>'T/T, L/C','certs'=>'CE, ISO 9001','img'=>'product_elec_1_5.jpg','featured'=>0],
    ['cat'=>4,'supplier_idx'=>3,'name'=>'Bluetooth 5.3 TWS Earbuds','slug'=>'bluetooth-53-tws-earbuds','desc'=>'Latest Bluetooth 5.3 true wireless stereo earbuds with active noise cancellation. Hi-Fi audio quality with 30 hours total playtime. IPX5 sweat-proof design.','specs'=>'Bluetooth: 5.3|ANC: -35dB|Playtime: 30h total|Rating: IPX5','moq'=>500,'unit'=>'Pieces','price'=>'$8 - $18 / Piece','supply'=>'100000 Pieces per Month','delivery'=>'5-10 days','packaging'=>'Color gift box','port'=>'Shenzhen Port','payment'=>'T/T, PayPal','certs'=>'CE, FCC, BQB','img'=>'product_elec_1_6.jpg','featured'=>0],
    ['cat'=>4,'supplier_idx'=>11,'name'=>'Waterproof Connector M12','slug'=>'waterproof-connector-m12','desc'=>'Industrial M12 waterproof connectors for automation and sensor applications. IP67/IP68 rated. Available in 3, 4, 5, 8, and 12 pin configurations. Panel and cable mount options.','specs'=>'Type: M12|Rating: IP67/IP68|Pins: 3-12|Current: Up to 4A','moq'=>500,'unit'=>'Pieces','price'=>'$0.80 - $3.50 / Piece','supply'=>'500000 Pieces per Month','delivery'=>'5-7 days','packaging'=>'Tray packing, anti-static bags','port'=>'Port Klang','payment'=>'T/T','certs'=>'UL, CE, IP67/IP68','img'=>'product_elec_1_7.jpg','featured'=>0],

    ['cat'=>5,'supplier_idx'=>8,'name'=>'CNC Vertical Machining Center','slug'=>'cnc-vertical-machining-center','desc'=>'High-precision CNC vertical machining center with Fanuc controller. 3-axis with optional 4th axis. Ideal for mold making, automotive parts, and precision engineering.','specs'=>'Travel: X800 Y500 Z500mm|Spindle: 12000 RPM|Tool: 24 ATC|Controller: Fanuc 0i-MF','moq'=>1,'unit'=>'Unit','price'=>'$35,000 - $65,000 / Unit','supply'=>'20 Units per Month','delivery'=>'45-60 days','packaging'=>'Wooden crate, sea-worthy','port'=>'Hamburg Port','payment'=>'T/T 30/70, L/C','certs'=>'CE, ISO 9001','img'=>'product_mach_1_1.jpg','featured'=>1],
    ['cat'=>5,'supplier_idx'=>8,'name'=>'Hydraulic Press Machine 200T','slug'=>'hydraulic-press-200t','desc'=>'Heavy-duty 200-ton hydraulic press for metal forming, stamping, and deep drawing operations. PLC controlled with safety light curtains. Energy-efficient servo hydraulic system.','specs'=>'Capacity: 200 Tons|Stroke: 300mm|Daylight: 600mm|Control: Siemens PLC','moq'=>1,'unit'=>'Unit','price'=>'$18,000 - $28,000 / Unit','supply'=>'10 Units per Month','delivery'=>'30-45 days','packaging'=>'Container loading','port'=>'Hamburg Port','payment'=>'T/T 30/70, L/C','certs'=>'CE, ISO 9001','img'=>'product_mach_1_2.jpg','featured'=>0],
    ['cat'=>5,'supplier_idx'=>8,'name'=>'Plastic Injection Molding Machine','slug'=>'plastic-injection-molding-machine','desc'=>'High-speed plastic injection molding machine with servo motor drive. Energy saving up to 60%. Suitable for packaging, automotive, and household products manufacturing.','specs'=>'Clamping: 100-500 Tons|Shot Weight: 50-2000g|Screw Dia: 36-75mm|Motor: Servo','moq'=>1,'unit'=>'Unit','price'=>'$25,000 - $85,000 / Unit','supply'=>'15 Units per Month','delivery'=>'30-45 days','packaging'=>'Open-top container','port'=>'Hamburg Port','payment'=>'T/T, L/C','certs'=>'CE, ISO 9001, EUROMAP','img'=>'product_mach_1_3.jpg','featured'=>1],
    ['cat'=>5,'supplier_idx'=>14,'name'=>'Digital Hardness Tester','slug'=>'digital-hardness-tester','desc'=>'Precision digital Rockwell hardness tester for metals and alloys. Automatic test cycle with digital display. Meets ASTM E18 and ISO 6508 standards.','specs'=>'Scale: HRA, HRB, HRC|Load: 60, 100, 150 kgf|Display: Digital LCD|Accuracy: ±0.5 HR','moq'=>5,'unit'=>'Units','price'=>'$2,500 - $5,000 / Unit','supply'=>'50 Units per Month','delivery'=>'14-21 days','packaging'=>'Foam-lined wooden case','port'=>'Kobe Port','payment'=>'T/T, L/C','certs'=>'ISO 6508, JIS B 7726','img'=>'product_mach_1_4.jpg','featured'=>0],
    ['cat'=>5,'supplier_idx'=>14,'name'=>'Optical Comparator Profile Projector','slug'=>'optical-comparator-profile-projector','desc'=>'High-precision optical profile projector for dimensional measurement and quality inspection. Digital readout with data output. Surface and contour illumination.','specs'=>'Screen: 300mm|Magnification: 10x, 20x, 50x|Travel: X150 Y100mm|Readout: 0.001mm','moq'=>3,'unit'=>'Units','price'=>'$4,000 - $8,000 / Unit','supply'=>'30 Units per Month','delivery'=>'14-21 days','packaging'=>'Protective crate','port'=>'Kobe Port','payment'=>'T/T, L/C','certs'=>'JIS B 7184, ISO 9001','img'=>'product_mach_1_5.jpg','featured'=>0],
    ['cat'=>5,'supplier_idx'=>8,'name'=>'Automatic Packaging Machine','slug'=>'automatic-packaging-machine','desc'=>'High-speed vertical form fill seal packaging machine for granules, powder, and liquids. Touch screen PLC control with multi-head weigher. Speed up to 80 bags per minute.','specs'=>'Speed: Up to 80 bags/min|Bag Size: W60-320mm L80-400mm|Film: PE, PP, PET|Control: Touch PLC','moq'=>1,'unit'=>'Unit','price'=>'$12,000 - $35,000 / Unit','supply'=>'20 Units per Month','delivery'=>'20-30 days','packaging'=>'Wooden case','port'=>'Hamburg Port','payment'=>'T/T, L/C','certs'=>'CE, ISO 9001','img'=>'product_mach_1_6.jpg','featured'=>0],

    ['cat'=>6,'supplier_idx'=>2,'name'=>'Industrial Grade Sodium Hydroxide','slug'=>'industrial-sodium-hydroxide','desc'=>'High-purity sodium hydroxide (caustic soda) flakes and pearls for industrial applications. Used in soap manufacturing, water treatment, paper production, and chemical processing.','specs'=>'Purity: 99% Min|Form: Flakes, Pearls|Moisture: 0.5% Max|Fe Content: 15ppm Max','moq'=>20,'unit'=>'Tons','price'=>'$350 - $450 / Ton','supply'=>'2000 Tons per Month','delivery'=>'10-15 days','packaging'=>'25kg bags on pallets or bulk','port'=>'Nhava Sheva Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, REACH','img'=>'product_chem_1_1.jpg','featured'=>0],
    ['cat'=>6,'supplier_idx'=>6,'name'=>'HDPE Granules Virgin Grade','slug'=>'hdpe-granules-virgin-grade','desc'=>'Virgin high-density polyethylene granules for blow molding, injection molding, and film extrusion. Excellent processability with high impact resistance and chemical stability.','specs'=>'MFI: 0.3-30 g/10min|Density: 0.941-0.965|Type: Blow, Injection, Film|Color: Natural','moq'=>25,'unit'=>'Tons','price'=>'$1,100 - $1,400 / Ton','supply'=>'5000 Tons per Month','delivery'=>'14-21 days','packaging'=>'25kg bags on pallets','port'=>'Jubail Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, FDA','img'=>'product_chem_1_2.jpg','featured'=>1],
    ['cat'=>6,'supplier_idx'=>2,'name'=>'Epoxy Resin System','slug'=>'epoxy-resin-system','desc'=>'Two-component epoxy resin system for coatings, adhesives, and composite applications. Excellent mechanical properties and chemical resistance. Various hardener options available.','specs'=>'Viscosity: 500-1500 cPs|Pot Life: 30-90 min|Shore Hardness: 80-85D|Cure: Room temp or heat','moq'=>1,'unit'=>'Tons','price'=>'$2,200 - $3,500 / Ton','supply'=>'500 Tons per Month','delivery'=>'10-15 days','packaging'=>'200L drums or 1000L IBC','port'=>'Nhava Sheva Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, REACH','img'=>'product_chem_1_3.jpg','featured'=>0],
    ['cat'=>6,'supplier_idx'=>6,'name'=>'PVC Resin Suspension Grade SG5','slug'=>'pvc-resin-sg5','desc'=>'Premium PVC resin suspension grade SG5 for pipe, profile, and sheet manufacturing. High molecular weight with excellent thermal stability. White powder form.','specs'=>'K Value: 66-68|Apparent Density: 0.45-0.55|Volatile: 0.3% Max|Whiteness: 80+','moq'=>25,'unit'=>'Tons','price'=>'$750 - $900 / Ton','supply'=>'3000 Tons per Month','delivery'=>'14-21 days','packaging'=>'25kg bags, 1 ton bags','port'=>'Jubail Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, SGS','img'=>'product_chem_1_4.jpg','featured'=>0],
    ['cat'=>6,'supplier_idx'=>2,'name'=>'Industrial Solvent IPA 99.5%','slug'=>'industrial-solvent-ipa','desc'=>'High-purity isopropyl alcohol (IPA) 99.5% for pharmaceutical, electronic, and industrial cleaning applications. Low water content with excellent solvent properties.','specs'=>'Purity: 99.5% Min|Water: 0.2% Max|Acidity: 0.002% Max|Specific Gravity: 0.786','moq'=>20,'unit'=>'Tons','price'=>'$800 - $1,100 / Ton','supply'=>'1000 Tons per Month','delivery'=>'7-14 days','packaging'=>'160kg drums, 1000L IBC, bulk','port'=>'Nhava Sheva Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, REACH, GMP','img'=>'product_chem_1_5.jpg','featured'=>0],
    ['cat'=>6,'supplier_idx'=>6,'name'=>'Industrial Lubricant Base Oil','slug'=>'industrial-lubricant-base-oil','desc'=>'High-quality Group II and Group III base oils for automotive and industrial lubricant manufacturing. Excellent thermal and oxidation stability. Low sulfur content.','specs'=>'Group: II/III|Viscosity: 4-12 cSt @100°C|Sulfur: <10ppm|Pour Point: -12°C','moq'=>100,'unit'=>'Tons','price'=>'$800 - $1,200 / Ton','supply'=>'10000 Tons per Month','delivery'=>'14-21 days','packaging'=>'Flexitank, ISO tank, drums','port'=>'Ras Tanura Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, API','img'=>'product_chem_1_6.jpg','featured'=>0],

    ['cat'=>7,'supplier_idx'=>19,'name'=>'Extruded Aluminum Profiles T6','slug'=>'extruded-aluminum-profiles-t6','desc'=>'Custom extruded aluminum profiles in 6000 series alloy with T6 temper. Wide range of cross-sections for architectural, industrial, and transportation applications.','specs'=>'Alloy: 6061/6063|Temper: T5/T6|Length: Up to 7m|Min Wall: 1.0mm','moq'=>2,'unit'=>'Tons','price'=>'$2,500 - $3,200 / Ton','supply'=>'500 Tons per Month','delivery'=>'15-20 days','packaging'=>'Stretch wrap on pallets','port'=>'Khalifa Bin Salman Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, ASTM B221','img'=>'product_metal_1_1.jpg','featured'=>1],
    ['cat'=>7,'supplier_idx'=>0,'name'=>'Hot Rolled Steel Coils HRC','slug'=>'hot-rolled-steel-coils-hrc','desc'=>'Premium quality hot rolled steel coils for automotive, shipbuilding, pipeline, and structural applications. Consistent mechanical properties across the full width and length.','specs'=>'Thickness: 1.2-25mm|Width: 1000-2000mm|Grade: Q235, SS400, S275|Standard: ASTM A36','moq'=>50,'unit'=>'Tons','price'=>'$500 - $700 / Ton','supply'=>'10000 Tons per Month','delivery'=>'15-25 days','packaging'=>'Eye-to-sky, strapped','port'=>'Jebel Ali Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, Mill Certificate','img'=>'product_metal_1_2.jpg','featured'=>0],
    ['cat'=>7,'supplier_idx'=>19,'name'=>'Copper Cathode 99.99% LME Grade','slug'=>'copper-cathode-9999-lme','desc'=>'LME registered brand copper cathodes with 99.99% purity. Full plate cathodes meeting BS EN 1978 and ASTM B115 standards. Ideal for wire rod and cable manufacturing.','specs'=>'Purity: 99.99%|Weight: 80-125kg/sheet|Size: 920x820mm|Standard: EN 1978','moq'=>25,'unit'=>'Tons','price'=>'Based on LME + premium','supply'=>'500 Tons per Month','delivery'=>'7-14 days','packaging'=>'Bundled on wooden pallets','port'=>'Khalifa Bin Salman Port','payment'=>'T/T, L/C','certs'=>'LME Registered, ISO 9001','img'=>'product_metal_1_3.jpg','featured'=>0],
    ['cat'=>7,'supplier_idx'=>0,'name'=>'Stainless Steel Sheet 304','slug'=>'stainless-steel-sheet-304','desc'=>'Cold rolled stainless steel sheets in grade 304 (18/8). Available in 2B, BA, and mirror finishes. Suitable for kitchen equipment, architectural cladding, and chemical tanks.','specs'=>'Grade: 304 (18Cr-8Ni)|Thickness: 0.5-6mm|Width: 1000, 1219, 1500mm|Finish: 2B, BA, Mirror','moq'=>5,'unit'=>'Tons','price'=>'$2,000 - $2,800 / Ton','supply'=>'3000 Tons per Month','delivery'=>'7-14 days','packaging'=>'Protective film, wooden pallet','port'=>'Jebel Ali Port','payment'=>'T/T, L/C','certs'=>'Mill Certificate, ISO 9001','img'=>'product_metal_1_4.jpg','featured'=>0],

    ['cat'=>8,'supplier_idx'=>13,'name'=>'Ceramic Disc Brake Pads Set','slug'=>'ceramic-disc-brake-pads-set','desc'=>'Premium ceramic brake pads for passenger vehicles. Low dust, low noise formula with excellent stopping power. Direct OE replacement. Suitable for European, Japanese, and Korean vehicles.','specs'=>'Type: Ceramic|Friction: FF rated|Temperature: Up to 400°C|Warranty: 50,000 km','moq'=>500,'unit'=>'Sets','price'=>'$5 - $15 / Set','supply'=>'50000 Sets per Month','delivery'=>'14-21 days','packaging'=>'Color box, 20 sets/master carton','port'=>'Felixstowe Port','payment'=>'T/T, L/C','certs'=>'ECE R90, ISO 9001','img'=>'product_auto_1_1.jpg','featured'=>1],
    ['cat'=>8,'supplier_idx'=>13,'name'=>'AGM Start-Stop Car Battery','slug'=>'agm-start-stop-car-battery','desc'=>'Advanced AGM car battery designed for start-stop vehicles. Superior cranking power with deep cycle capability. Maintenance-free with spill-proof design. 3-year warranty.','specs'=>'Capacity: 60-100Ah|CCA: 600-900A|Type: AGM|Voltage: 12V','moq'=>200,'unit'=>'Pieces','price'=>'$65 - $120 / Piece','supply'=>'10000 Pieces per Month','delivery'=>'14-21 days','packaging'=>'Individual box on pallet','port'=>'Felixstowe Port','payment'=>'T/T, L/C','certs'=>'IEC 60095, TUV','img'=>'product_auto_1_2.jpg','featured'=>0],
    ['cat'=>8,'supplier_idx'=>13,'name'=>'Suspension Coil Springs','slug'=>'suspension-coil-springs','desc'=>'OE quality suspension coil springs for passenger cars and light commercial vehicles. Shot-peened and epoxy-coated for corrosion resistance. Available for 5000+ applications.','specs'=>'Material: Chrome Vanadium|Coating: Epoxy Powder|Applications: 5000+|Warranty: 2 years','moq'=>300,'unit'=>'Pieces','price'=>'$8 - $25 / Piece','supply'=>'30000 Pieces per Month','delivery'=>'14-21 days','packaging'=>'Shrink wrapped pairs in carton','port'=>'Felixstowe Port','payment'=>'T/T, L/C','certs'=>'ISO/TS 16949, IATF','img'=>'product_auto_1_3.jpg','featured'=>0],
    ['cat'=>8,'supplier_idx'=>13,'name'=>'LED Headlight Bulb Kit H7','slug'=>'led-headlight-bulb-kit-h7','desc'=>'High-performance LED headlight conversion kit. 300% brighter than halogen with perfect beam pattern. 50,000 hour lifespan. Plug-and-play installation with built-in driver.','specs'=>'Lumens: 12000LM/pair|Color: 6000K White|Wattage: 55W/pair|Lifespan: 50,000 hours','moq'=>500,'unit'=>'Pairs','price'=>'$12 - $28 / Pair','supply'=>'50000 Pairs per Month','delivery'=>'7-14 days','packaging'=>'Color retail box','port'=>'Felixstowe Port','payment'=>'T/T, PayPal','certs'=>'CE, E-Mark, RoHS','img'=>'product_auto_1_4.jpg','featured'=>0],

    ['cat'=>9,'supplier_idx'=>9,'name'=>'Disposable Nitrile Exam Gloves','slug'=>'disposable-nitrile-exam-gloves','desc'=>'Medical-grade powder-free nitrile examination gloves. Textured fingertips for superior grip. AQL 1.5. Available in blue, black, and white. Sizes XS to XL.','specs'=>'Material: Nitrile|Powder: Free|AQL: 1.5|Thickness: 3.5-5 mil','moq'=>100,'unit'=>'Cases (1000pcs)','price'=>'$38 - $55 / Case','supply'=>'5000 Cases per Month','delivery'=>'14-21 days','packaging'=>'100pcs/box, 10 boxes/case','port'=>'Chicago Port','payment'=>'T/T, L/C','certs'=>'FDA 510(k), EN 455, ASTM D6319','img'=>'product_med_1_1.jpg','featured'=>1],
    ['cat'=>9,'supplier_idx'=>9,'name'=>'Digital Blood Pressure Monitor','slug'=>'digital-blood-pressure-monitor','desc'=>'Clinically validated automatic upper arm blood pressure monitor. Large LCD display with irregular heartbeat detection. Memory for 2 users x 120 readings. USB rechargeable.','specs'=>'Method: Oscillometric|Accuracy: ±3mmHg|Memory: 2x120|Cuff: 22-42cm','moq'=>200,'unit'=>'Pieces','price'=>'$18 - $35 / Piece','supply'=>'10000 Pieces per Month','delivery'=>'10-14 days','packaging'=>'Gift box with carrying case','port'=>'Chicago Port','payment'=>'T/T, L/C','certs'=>'FDA, CE, ISO 13485','img'=>'product_med_1_2.jpg','featured'=>0],
    ['cat'=>9,'supplier_idx'=>18,'name'=>'Paracetamol Tablets BP 500mg','slug'=>'paracetamol-tablets-bp-500mg','desc'=>'Pharmaceutical-grade paracetamol (acetaminophen) tablets 500mg. Manufactured in WHO-GMP certified facility. Available in various pack sizes for retail and hospital supply.','specs'=>'Strength: 500mg|Standard: BP/USP|Shelf Life: 36 months|Packaging: Blister, Bottle','moq'=>10000,'unit'=>'Boxes','price'=>'$0.50 - $1.20 / Box (10 tabs)','supply'=>'500000 Boxes per Month','delivery'=>'21-30 days','packaging'=>'Blister pack in printed carton','port'=>'Mundra Port','payment'=>'T/T, L/C','certs'=>'WHO-GMP, ISO 9001, FDA','img'=>'product_med_1_3.jpg','featured'=>0],
    ['cat'=>9,'supplier_idx'=>9,'name'=>'Portable Pulse Oximeter','slug'=>'portable-pulse-oximeter','desc'=>'Fingertip pulse oximeter with OLED display showing SpO2, pulse rate, and plethysmogram. 10-second measurement time. Auto power-off. Suitable for clinical and home use.','specs'=>'SpO2 Range: 70-100%|Accuracy: ±2%|PR Range: 30-250 BPM|Power: 2x AAA','moq'=>500,'unit'=>'Pieces','price'=>'$6 - $15 / Piece','supply'=>'50000 Pieces per Month','delivery'=>'7-10 days','packaging'=>'Individual box with lanyard','port'=>'Chicago Port','payment'=>'T/T, PayPal','certs'=>'FDA, CE, ISO 13485','img'=>'product_med_1_4.jpg','featured'=>0],
    ['cat'=>9,'supplier_idx'=>18,'name'=>'Herbal Ashwagandha Extract Capsules','slug'=>'herbal-ashwagandha-extract-capsules','desc'=>'Standardized Ashwagandha root extract capsules (5% withanolides). Natural stress relief and energy support supplement. Vegetarian capsules with no artificial additives.','specs'=>'Strength: 500mg|Extract: 5% Withanolides|Capsule: Vegetarian HPMC|Count: 60 capsules/bottle','moq'=>5000,'unit'=>'Bottles','price'=>'$2.50 - $5.00 / Bottle','supply'=>'100000 Bottles per Month','delivery'=>'14-21 days','packaging'=>'HDPE bottle in printed carton','port'=>'Mundra Port','payment'=>'T/T, L/C','certs'=>'GMP, ISO 22000, Halal','img'=>'product_med_1_5.jpg','featured'=>0],

    ['cat'=>10,'supplier_idx'=>10,'name'=>'Modern Leather Sectional Sofa','slug'=>'modern-leather-sectional-sofa','desc'=>'Premium genuine leather L-shaped sectional sofa with adjustable headrests. High-density foam cushions for exceptional comfort. Solid wood frame with chrome legs. Available in multiple colors.','specs'=>'Material: Top Grain Leather|Frame: Solid Wood|Dimensions: 300x180x90cm|Weight: 120kg','moq'=>20,'unit'=>'Sets','price'=>'$800 - $1,500 / Set','supply'=>'200 Sets per Month','delivery'=>'30-45 days','packaging'=>'Disassembled in carton boxes','port'=>'Nansha Port','payment'=>'T/T 30/70, L/C','certs'=>'ISO 9001, BIFMA','img'=>'product_home_1_1.jpg','featured'=>1],
    ['cat'=>10,'supplier_idx'=>10,'name'=>'Solid Wood Dining Table Set','slug'=>'solid-wood-dining-table-set','desc'=>'8-seater solid wood dining table with matching chairs. Made from premium oak or walnut. Elegant mid-century modern design. Professional wood finish with UV protection.','specs'=>'Material: Oak/Walnut Solid Wood|Table Size: 200x90x75cm|Chairs: 8 included|Finish: Lacquered','moq'=>30,'unit'=>'Sets','price'=>'$450 - $900 / Set','supply'=>'150 Sets per Month','delivery'=>'30-45 days','packaging'=>'KD packed in reinforced cartons','port'=>'Nansha Port','payment'=>'T/T, L/C','certs'=>'FSC, ISO 9001','img'=>'product_home_1_2.jpg','featured'=>0],
    ['cat'=>10,'supplier_idx'=>12,'name'=>'Handwoven Wool Area Rug','slug'=>'handwoven-wool-area-rug','desc'=>'Traditional handwoven wool area rugs with intricate oriental patterns. Each rug is hand-knotted by skilled artisans. 100% New Zealand wool pile on cotton foundation. Sizes available from 4x6 to 12x15 feet.','specs'=>'Pile: 100% NZ Wool|Foundation: Cotton|Knots: 120-200 per sq inch|Sizes: 4x6 to 12x15 ft','moq'=>10,'unit'=>'Pieces','price'=>'$200 - $2,000 / Piece','supply'=>'500 Pieces per Month','delivery'=>'45-60 days','packaging'=>'Rolled in poly wrap','port'=>'Nhava Sheva Port','payment'=>'T/T, L/C','certs'=>'GoodWeave, ISO 9001','img'=>'product_home_1_3.jpg','featured'=>1],
    ['cat'=>10,'supplier_idx'=>12,'name'=>'Brass Table Lamp Collection','slug'=>'brass-table-lamp-collection','desc'=>'Handcrafted brass table lamps with intricate jali work and patina finishes. Traditional Rajasthani designs with modern E27 fittings. Perfect for luxury hospitality and home decor.','specs'=>'Material: Solid Brass|Height: 30-60cm|Bulb: E27 (not included)|Finish: Antique, Polished','moq'=>50,'unit'=>'Pieces','price'=>'$25 - $80 / Piece','supply'=>'2000 Pieces per Month','delivery'=>'21-30 days','packaging'=>'Individual box with foam insert','port'=>'Nhava Sheva Port','payment'=>'T/T','certs'=>'CE (wiring)','img'=>'product_home_1_4.jpg','featured'=>0],
    ['cat'=>10,'supplier_idx'=>10,'name'=>'Ergonomic Office Chair','slug'=>'ergonomic-office-chair','desc'=>'Professional ergonomic mesh office chair with adjustable lumbar support, 4D armrests, and synchronized tilt mechanism. Breathable mesh backrest with padded seat. 5-year warranty.','specs'=>'Max Load: 150kg|Seat Height: 42-52cm|Armrest: 4D|Back: High-density Mesh','moq'=>50,'unit'=>'Pieces','price'=>'$80 - $200 / Piece','supply'=>'2000 Pieces per Month','delivery'=>'14-21 days','packaging'=>'KD in carton, 1pc/carton','port'=>'Nansha Port','payment'=>'T/T, L/C','certs'=>'BIFMA, ISO 9001','img'=>'product_home_1_5.jpg','featured'=>0],

    ['cat'=>11,'supplier_idx'=>16,'name'=>'Commercial Treadmill Heavy Duty','slug'=>'commercial-treadmill-heavy-duty','desc'=>'Professional-grade commercial treadmill with 4.0HP AC motor. 22-inch wide belt with cushioned deck system. Built-in programs, heart rate monitoring, and entertainment console.','specs'=>'Motor: 4.0HP AC|Speed: 0.5-20 km/h|Incline: 0-15%|Belt: 56x152cm','moq'=>10,'unit'=>'Units','price'=>'$1,800 - $3,500 / Unit','supply'=>'200 Units per Month','delivery'=>'21-30 days','packaging'=>'Assembled in wooden crate','port'=>'Busan Port','payment'=>'T/T, L/C','certs'=>'CE, EN 957, ISO 20957','img'=>'product_sport_1_1.jpg','featured'=>1],
    ['cat'=>11,'supplier_idx'=>16,'name'=>'Adjustable Dumbbell Set 5-52.5 lbs','slug'=>'adjustable-dumbbell-set','desc'=>'Space-saving adjustable dumbbell set with quick-change dial system. Replaces 15 sets of fixed dumbbells. From 5 to 52.5 lbs per dumbbell. Includes storage cradle.','specs'=>'Range: 5-52.5 lbs each|Increments: 2.5 lbs|Material: Steel/Nylon|Includes: 2 dumbbells + cradle','moq'=>100,'unit'=>'Sets','price'=>'$150 - $280 / Set','supply'=>'2000 Sets per Month','delivery'=>'14-21 days','packaging'=>'Color box with foam insert','port'=>'Busan Port','payment'=>'T/T','certs'=>'CE, ASTM F2216','img'=>'product_sport_1_2.jpg','featured'=>0],
    ['cat'=>11,'supplier_idx'=>16,'name'=>'Premium Natural Rubber Yoga Mat','slug'=>'premium-natural-rubber-yoga-mat','desc'=>'Eco-friendly natural rubber yoga mat with microfiber suede top. Excellent grip even with sweat. 5mm thickness for joint protection. Available in 12 designs.','specs'=>'Material: Natural Rubber + Suede|Thickness: 5mm|Size: 183x68cm|Weight: 2.5kg','moq'=>500,'unit'=>'Pieces','price'=>'$12 - $25 / Piece','supply'=>'10000 Pieces per Month','delivery'=>'14-21 days','packaging'=>'Carry strap, printed box','port'=>'Busan Port','payment'=>'T/T, PayPal','certs'=>'SGS, OEKO-TEX','img'=>'product_sport_1_3.jpg','featured'=>0],
    ['cat'=>11,'supplier_idx'=>16,'name'=>'Resistance Bands Set 5 Levels','slug'=>'resistance-bands-set-5-levels','desc'=>'Professional latex resistance bands set with 5 resistance levels. Includes door anchor, ankle straps, and handles. Perfect for home workouts, physiotherapy, and strength training.','specs'=>'Levels: 5 (10-50 lbs)|Material: Natural Latex|Length: 120cm|Includes: Anchor, Straps, Handles','moq'=>1000,'unit'=>'Sets','price'=>'$4 - $10 / Set','supply'=>'50000 Sets per Month','delivery'=>'7-14 days','packaging'=>'Carry bag in color box','port'=>'Busan Port','payment'=>'T/T, PayPal','certs'=>'SGS, CE','img'=>'product_sport_1_4.jpg','featured'=>0],

    ['cat'=>12,'supplier_idx'=>17,'name'=>'Custom Corrugated Shipping Boxes','slug'=>'custom-corrugated-shipping-boxes','desc'=>'Custom-printed corrugated shipping boxes in all sizes and flute types. Full-color CMYK printing available. Suitable for e-commerce, retail, and industrial packaging.','specs'=>'Material: B, C, BC flute|Printing: Up to 6 colors|Min Size: 10x10x5cm|Max Size: 120x80x80cm','moq'=>1000,'unit'=>'Pieces','price'=>'$0.30 - $3.00 / Piece','supply'=>'500000 Pieces per Month','delivery'=>'10-14 days','packaging'=>'Flat packed on pallets','port'=>'Santos Port','payment'=>'T/T','certs'=>'FSC, ISO 9001','img'=>'product_pack_1_1.jpg','featured'=>1],
    ['cat'=>12,'supplier_idx'=>17,'name'=>'Flexible Packaging Pouches','slug'=>'flexible-packaging-pouches','desc'=>'Custom printed stand-up pouches with zipper closure. Multi-layer laminated film for food, coffee, snacks, and pet food. High barrier against moisture and oxygen.','specs'=>'Material: PET/AL/PE|Closure: Zipper|Printing: Rotogravure 10-color|Barrier: High (OTR<1)','moq'=>5000,'unit'=>'Pieces','price'=>'$0.05 - $0.50 / Piece','supply'=>'2000000 Pieces per Month','delivery'=>'14-21 days','packaging'=>'Rolls or flat in cartons','port'=>'Santos Port','payment'=>'T/T, L/C','certs'=>'FDA, ISO 22000, BRC','img'=>'product_pack_1_2.jpg','featured'=>0],
    ['cat'=>12,'supplier_idx'=>17,'name'=>'Self-Adhesive Product Labels','slug'=>'self-adhesive-product-labels','desc'=>'Custom self-adhesive labels on rolls. Digital and flexographic printing. Materials include paper, PP, PET, and vinyl. Die-cut to any shape. UV-resistant inks available.','specs'=>'Material: Paper, PP, PET, Vinyl|Printing: Digital, Flexo|Finish: Gloss, Matte, Foil|Roll: 1000-10000 labels','moq'=>5000,'unit'=>'Pieces','price'=>'$0.02 - $0.15 / Piece','supply'=>'5000000 Pieces per Month','delivery'=>'7-10 days','packaging'=>'Rolls in carton boxes','port'=>'Santos Port','payment'=>'T/T','certs'=>'ISO 9001, FSC','img'=>'product_pack_1_3.jpg','featured'=>0],
    ['cat'=>12,'supplier_idx'=>17,'name'=>'Kraft Paper Shopping Bags','slug'=>'kraft-paper-shopping-bags','desc'=>'Eco-friendly brown and white kraft paper shopping bags with twisted rope handles. Custom printing available. Ideal for retail stores, boutiques, and restaurants.','specs'=>'Material: Kraft Paper 120-250gsm|Handle: Twisted Rope|Printing: Up to 4 colors|Sizes: Small to Jumbo','moq'=>3000,'unit'=>'Pieces','price'=>'$0.15 - $0.80 / Piece','supply'=>'200000 Pieces per Month','delivery'=>'10-14 days','packaging'=>'Flat packed in bundles','port'=>'Santos Port','payment'=>'T/T','certs'=>'FSC, ISO 14001','img'=>'product_pack_1_4.jpg','featured'=>0],

    ['cat'=>2,'supplier_idx'=>7,'name'=>'Dried Turmeric Finger Whole','slug'=>'dried-turmeric-finger-whole','desc'=>'Premium quality dried turmeric fingers with high curcumin content (3-5%). Bright yellow-orange color with aromatic flavor. Organically grown and sun-dried.','specs'=>'Curcumin: 3-5%|Moisture: 10% Max|Length: 5-7cm|Origin: Vietnam Highlands','moq'=>5,'unit'=>'Tons','price'=>'$1,800 - $2,500 / Ton','supply'=>'200 Tons per Month','delivery'=>'10-14 days','packaging'=>'25kg PP bags, bulk bags','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'USDA Organic, HACCP','img'=>'product_agri_1_5.jpg','featured'=>0],

    ['cat'=>3,'supplier_idx'=>1,'name'=>'Organic Cotton Canvas Fabric','slug'=>'organic-cotton-canvas-fabric','desc'=>'Heavy-weight organic cotton canvas fabric ideal for bags, upholstery, and workwear. GOTS certified. Available in natural and 20+ dyed colors. Width 58-60 inches.','specs'=>'Weight: 10-16 oz/yd|Width: 58-60 inches|Composition: 100% Organic Cotton|Weave: Plain','moq'=>2000,'unit'=>'Meters','price'=>'$3.50 - $6.00 / Meter','supply'=>'50000 Meters per Month','delivery'=>'21-30 days','packaging'=>'Rolled on tubes','port'=>'Karachi Port','payment'=>'T/T, L/C','certs'=>'GOTS, OEKO-TEX','img'=>'product_textile_1_7.jpg','featured'=>0],

    ['cat'=>4,'supplier_idx'=>3,'name'=>'Outdoor P4 LED Display Cabinet','slug'=>'outdoor-p4-led-display-cabinet','desc'=>'Weatherproof outdoor LED display cabinet with P4 pixel pitch. IP65 rated front and back. High brightness 6500 nits for direct sunlight visibility. Anti-corrosion die-cast aluminum.','specs'=>'Pixel Pitch: 4mm|Brightness: 6500 nits|IP Rating: IP65|Cabinet: Die-cast Aluminum','moq'=>5,'unit'=>'Square Meters','price'=>'$450 - $700 / Square Meter','supply'=>'3000 Square Meters per Month','delivery'=>'10-14 days','packaging'=>'Flight case','port'=>'Shenzhen Port','payment'=>'T/T, L/C','certs'=>'CE, FCC, RoHS, IP65','img'=>'product_elec_1_8.jpg','featured'=>0],

    ['cat'=>5,'supplier_idx'=>8,'name'=>'Laser Cutting Machine 3kW Fiber','slug'=>'laser-cutting-machine-3kw','desc'=>'3kW fiber laser cutting machine for metal sheet processing. High-speed cutting of steel, stainless steel, aluminum, brass. IPG laser source with Cypcut controller.','specs'=>'Power: 3000W|Cutting Area: 3000x1500mm|Speed: Up to 40m/min|Source: IPG Fiber','moq'=>1,'unit'=>'Unit','price'=>'$28,000 - $55,000 / Unit','supply'=>'10 Units per Month','delivery'=>'30-45 days','packaging'=>'Wooden crate, containerized','port'=>'Hamburg Port','payment'=>'T/T 30/70, L/C','certs'=>'CE, ISO 9001, FDA (laser)','img'=>'product_mach_1_7.jpg','featured'=>0],

    ['cat'=>7,'supplier_idx'=>0,'name'=>'Seamless Steel Tubes ASTM A106','slug'=>'seamless-steel-tubes-a106','desc'=>'Seamless carbon steel tubes for high-temperature service. ASTM A106 Grade B. Suitable for refineries, power plants, and boiler applications. Full length tested.','specs'=>'Grade: A106 Gr.B|OD: 21.3-508mm|Wall: 2.77-50mm|Length: 5.8-12m','moq'=>25,'unit'=>'Tons','price'=>'$700 - $1,100 / Ton','supply'=>'3000 Tons per Month','delivery'=>'14-21 days','packaging'=>'Bundled, end caps','port'=>'Jebel Ali Port','payment'=>'T/T, L/C','certs'=>'API 5L, ASTM A106, ISO 9001','img'=>'product_metal_1_5.jpg','featured'=>0],

    ['cat'=>9,'supplier_idx'=>9,'name'=>'Infrared Forehead Thermometer','slug'=>'infrared-forehead-thermometer','desc'=>'Non-contact infrared forehead thermometer with 1-second reading. Large backlit LCD with color-coded fever alert. Memory for 50 readings. Switchable °F/°C.','specs'=>'Range: 32-42.9°C|Accuracy: ±0.2°C|Distance: 1-5cm|Memory: 50 readings','moq'=>500,'unit'=>'Pieces','price'=>'$5 - $12 / Piece','supply'=>'50000 Pieces per Month','delivery'=>'5-10 days','packaging'=>'Color box, 50pcs/master carton','port'=>'Chicago Port','payment'=>'T/T, PayPal','certs'=>'FDA, CE, ISO 13485','img'=>'product_med_1_6.jpg','featured'=>0],

    ['cat'=>10,'supplier_idx'=>12,'name'=>'Hand-Carved Marble Artifacts','slug'=>'hand-carved-marble-artifacts','desc'=>'Exquisite hand-carved white marble artifacts and decorative items. Traditional Mughal designs including vases, plates, boxes, and figurines with semi-precious stone inlay work.','specs'=>'Material: White Makrana Marble|Inlay: Semi-precious Stones|Height: 15-60cm|Handmade: Yes','moq'=>20,'unit'=>'Pieces','price'=>'$15 - $200 / Piece','supply'=>'1000 Pieces per Month','delivery'=>'30-45 days','packaging'=>'Foam box, double carton','port'=>'Nhava Sheva Port','payment'=>'T/T','certs'=>'Handcraft Certificate','img'=>'product_home_1_6.jpg','featured'=>0],

    ['cat'=>11,'supplier_idx'=>16,'name'=>'Multi-Station Home Gym System','slug'=>'multi-station-home-gym-system','desc'=>'All-in-one multi-station home gym with lat pulldown, chest press, leg extension, and cable crossover. 200 lb weight stack with smooth cable pulleys.','specs'=>'Stations: 5+|Weight Stack: 200 lbs|Cable Ratio: 2:1|Frame: 11-gauge Steel','moq'=>10,'unit'=>'Units','price'=>'$800 - $2,000 / Unit','supply'=>'100 Units per Month','delivery'=>'21-30 days','packaging'=>'KD in reinforced cartons','port'=>'Busan Port','payment'=>'T/T, L/C','certs'=>'CE, EN 957, ASTM','img'=>'product_sport_1_5.jpg','featured'=>0],

    ['cat'=>12,'supplier_idx'=>17,'name'=>'Biodegradable Food Containers','slug'=>'biodegradable-food-containers','desc'=>'Eco-friendly biodegradable food containers made from sugarcane bagasse. Microwave and freezer safe. Compostable within 90 days. Perfect for takeaway restaurants and catering.','specs'=>'Material: Sugarcane Bagasse|Sizes: 500-1000ml|Microwave: Safe|Compostable: 90 days','moq'=>5000,'unit'=>'Pieces','price'=>'$0.06 - $0.20 / Piece','supply'=>'1000000 Pieces per Month','delivery'=>'10-14 days','packaging'=>'Stacked in carton boxes','port'=>'Santos Port','payment'=>'T/T','certs'=>'FDA, BPI, EN 13432','img'=>'product_pack_1_5.jpg','featured'=>0],

    ['cat'=>1,'supplier_idx'=>5,'name'=>'Onyx Stone Decorative Panels','slug'=>'onyx-stone-decorative-panels','desc'=>'Translucent onyx stone panels for backlit walls and countertops. Stunning honey, green, and white onyx varieties. Creates a dramatic luminous effect when backlit.','specs'=>'Thickness: 10-20mm|Size: 120x60cm|Finish: Polished|Types: Honey, Green, White','moq'=>20,'unit'=>'Square Meters','price'=>'$150 - $400 / Square Meter','supply'=>'500 Square Meters per Month','delivery'=>'20-30 days','packaging'=>'Wooden crate, foam sheets','port'=>'Mersin Port','payment'=>'T/T, L/C','certs'=>'CE Certified','img'=>'product_build_1_9.jpg','featured'=>0],

    ['cat'=>6,'supplier_idx'=>2,'name'=>'Polyurethane Foam Spray System','slug'=>'polyurethane-foam-spray-system','desc'=>'Two-component spray polyurethane foam for insulation and sealing. Closed-cell and open-cell options. R-value of 6.5 per inch. Fire-retardant formulations available.','specs'=>'Type: Closed Cell / Open Cell|R-Value: 6.5/inch|Density: 28-32 kg/m³|Fire Rating: Class 1','moq'=>5,'unit'=>'Tons','price'=>'$2,800 - $4,000 / Ton','supply'=>'200 Tons per Month','delivery'=>'10-15 days','packaging'=>'200L drums, A+B sets','port'=>'Nhava Sheva Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, UL, FM','img'=>'product_chem_1_7.jpg','featured'=>0],

    ['cat'=>7,'supplier_idx'=>19,'name'=>'Wrought Iron Gates Custom Design','slug'=>'wrought-iron-gates-custom','desc'=>'Custom-designed wrought iron gates for villas, compounds, and commercial properties. Hand-forged scrollwork with powder-coated finish. Includes automation-ready mounting.','specs'=>'Material: Mild Steel|Finish: Hot-dip Galvanized + Powder Coat|Height: Up to 4m|Width: Custom','moq'=>5,'unit'=>'Pieces','price'=>'$500 - $3,000 / Piece','supply'=>'100 Pieces per Month','delivery'=>'21-30 days','packaging'=>'Crated for shipping','port'=>'Khalifa Bin Salman Port','payment'=>'T/T','certs'=>'ISO 9001','img'=>'product_metal_1_6.jpg','featured'=>0],

    ['cat'=>8,'supplier_idx'=>13,'name'=>'Windshield Wiper Blades Universal','slug'=>'windshield-wiper-blades-universal','desc'=>'Universal flat windshield wiper blades with multi-adapter system. Natural rubber element with Teflon coating for smooth, streak-free wiping. 10 sizes from 14" to 28".','specs'=>'Type: Flat Blade|Material: Natural Rubber + Teflon|Sizes: 14-28 inches|Adapters: 10 types','moq'=>500,'unit'=>'Pieces','price'=>'$1.50 - $4.00 / Piece','supply'=>'100000 Pieces per Month','delivery'=>'7-14 days','packaging'=>'Blister pack, 50pcs/master carton','port'=>'Felixstowe Port','payment'=>'T/T','certs'=>'ECE R43, ISO 9001','img'=>'product_auto_1_5.jpg','featured'=>0],

    ['cat'=>2,'supplier_idx'=>7,'name'=>'Coconut Desiccated Fine Grade','slug'=>'coconut-desiccated-fine-grade','desc'=>'Premium desiccated coconut in fine, medium, and flake grades. Made from fresh mature coconut meat. Pure white with natural coconut aroma. Ideal for confectionery and baking.','specs'=>'Fat Content: 60-65%|Moisture: 2.5% Max|Particle Size: Fine, Medium, Flake|Color: White','moq'=>10,'unit'=>'Tons','price'=>'$1,400 - $1,800 / Ton','supply'=>'500 Tons per Month','delivery'=>'14-21 days','packaging'=>'25kg multi-wall paper bags','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'HACCP, BRC, Kosher','img'=>'product_agri_1_6.jpg','featured'=>0],

    ['cat'=>3,'supplier_idx'=>4,'name'=>'Sports Performance Activewear','slug'=>'sports-performance-activewear','desc'=>'High-performance moisture-wicking activewear made from recycled polyester blend. 4-way stretch fabric with flatlock seams. Sublimation printing for custom team uniforms.','specs'=>'Fabric: Recycled Polyester/Spandex|Weight: 180-220 GSM|Technology: Moisture Wicking|Printing: Sublimation','moq'=>500,'unit'=>'Pieces','price'=>'$5 - $12 / Piece','supply'=>'20000 Pieces per Month','delivery'=>'30-45 days','packaging'=>'Individual poly bag','port'=>'Chittagong Port','payment'=>'T/T, L/C','certs'=>'GRS, OEKO-TEX, BSCI','img'=>'product_textile_1_8.jpg','featured'=>0],

    ['cat'=>5,'supplier_idx'=>14,'name'=>'Coordinate Measuring Machine CMM','slug'=>'coordinate-measuring-machine-cmm','desc'=>'Bridge-type coordinate measuring machine for precision 3D measurement. Renishaw touch-trigger probe system. Automatic probe changer. PC-DMIS software included.','specs'=>'Range: 700x1000x600mm|Accuracy: 2.5+L/300 μm|Probe: Renishaw TP20|Software: PC-DMIS','moq'=>1,'unit'=>'Unit','price'=>'$45,000 - $90,000 / Unit','supply'=>'5 Units per Month','delivery'=>'30-45 days','packaging'=>'Climate-controlled wooden crate','port'=>'Kobe Port','payment'=>'T/T, L/C','certs'=>'ISO 10360, JIS B 7440','img'=>'product_mach_1_8.jpg','featured'=>0],

    ['cat'=>9,'supplier_idx'=>18,'name'=>'Multivitamin Tablets Daily Formula','slug'=>'multivitamin-tablets-daily-formula','desc'=>'Comprehensive daily multivitamin and mineral supplement tablets. Contains 23 essential nutrients including vitamins A, B-complex, C, D3, E, zinc, and iron. Film-coated for easy swallowing.','specs'=>'Nutrients: 23|Form: Film-coated Tablet|Serving: 1 tablet daily|Count: 60, 90, 120 tablets','moq'=>5000,'unit'=>'Bottles','price'=>'$1.50 - $4.00 / Bottle','supply'=>'200000 Bottles per Month','delivery'=>'14-21 days','packaging'=>'HDPE bottle in printed box','port'=>'Mundra Port','payment'=>'T/T, L/C','certs'=>'GMP, ISO 22000, FDA','img'=>'product_med_1_7.jpg','featured'=>0],

    ['cat'=>10,'supplier_idx'=>10,'name'=>'Executive Office Desk L-Shape','slug'=>'executive-office-desk-l-shape','desc'=>'Premium L-shaped executive office desk with cable management. Melamine-faced MDF with scratch-resistant surface. Modesty panel and integrated wire channels. Available in walnut and grey oak.','specs'=>'Material: MFC MDF|Dimensions: 180x160x75cm|Colors: Walnut, Grey Oak|Load: 100kg','moq'=>30,'unit'=>'Pieces','price'=>'$150 - $350 / Piece','supply'=>'500 Pieces per Month','delivery'=>'14-21 days','packaging'=>'Flat packed 2 cartons/desk','port'=>'Nansha Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, E1 Board','img'=>'product_home_1_7.jpg','featured'=>0],

    ['cat'=>6,'supplier_idx'=>6,'name'=>'Titanium Dioxide Rutile Grade','slug'=>'titanium-dioxide-rutile-grade','desc'=>'High-quality titanium dioxide (TiO2) rutile grade for paint, coating, plastic, and paper industries. Excellent whiteness, hiding power, and weather resistance.','specs'=>'TiO2 Content: 94% Min|Type: Rutile|Particle Size: 0.2-0.3 μm|Whiteness: 97+','moq'=>10,'unit'=>'Tons','price'=>'$2,200 - $2,800 / Ton','supply'=>'1000 Tons per Month','delivery'=>'14-21 days','packaging'=>'25kg bags on pallets','port'=>'Jubail Port','payment'=>'T/T, L/C','certs'=>'ISO 9001, REACH, FDA','img'=>'product_chem_1_8.jpg','featured'=>0],

    ['cat'=>7,'supplier_idx'=>0,'name'=>'Galvanized Steel Wire Rope','slug'=>'galvanized-steel-wire-rope','desc'=>'Hot-dip galvanized steel wire ropes for lifting, marine, and construction applications. Available in 6x19, 6x36, and 7x19 constructions. Wire strand core or fiber core options.','specs'=>'Construction: 6x19, 6x36, 7x19|Diameter: 6-52mm|Grade: 1770 MPa|Core: WSC, FC','moq'=>10,'unit'=>'Tons','price'=>'$1,200 - $1,800 / Ton','supply'=>'500 Tons per Month','delivery'=>'10-14 days','packaging'=>'Wooden reels','port'=>'Jebel Ali Port','payment'=>'T/T, L/C','certs'=>'API 9A, ISO 2408','img'=>'product_metal_1_7.jpg','featured'=>0],

    ['cat'=>2,'supplier_idx'=>7,'name'=>'Organic Green Tea Leaves','slug'=>'organic-green-tea-leaves','desc'=>'Premium organic green tea leaves from highland plantations. Carefully hand-picked and processed for maximum antioxidant content. Available in loose leaf and CTC grades.','specs'=>'Type: Green Tea|Grade: OP, Fannings, CTC|Moisture: 6% Max|Origin: Thai Nguyen Province','moq'=>5,'unit'=>'Tons','price'=>'$3,500 - $6,000 / Ton','supply'=>'100 Tons per Month','delivery'=>'10-14 days','packaging'=>'Paper bags lined with foil','port'=>'Cat Lai Port','payment'=>'T/T, L/C','certs'=>'USDA Organic, EU Organic, ISO 22000','img'=>'product_agri_1_7.jpg','featured'=>0],

    ['cat'=>12,'supplier_idx'=>17,'name'=>'Shrink Wrap Film Rolls','slug'=>'shrink-wrap-film-rolls','desc'=>'Cross-linked POF shrink wrap film for product packaging. Crystal clear with high gloss. Suitable for food, cosmetics, and retail products. Available in center-fold and single wound.','specs'=>'Material: POF Cross-linked|Thickness: 12-25 micron|Width: 150-800mm|Length: 500-3000m','moq'=>100,'unit'=>'Rolls','price'=>'$2.50 - $8.00 / Roll','supply'=>'50000 Rolls per Month','delivery'=>'7-10 days','packaging'=>'Carton boxes on pallets','port'=>'Santos Port','payment'=>'T/T','certs'=>'FDA, EU 10/2011','img'=>'product_pack_1_6.jpg','featured'=>0],
];

echo "\nInserting " . count($products) . " products...\n";
$prodCount = 0;

foreach ($products as $p) {
    $suppIdx = $p['supplier_idx'];
    if (!isset($supplierIds[$suppIdx]) || $supplierIds[$suppIdx] === null) {
        echo "  SKIP: Supplier index {$suppIdx} not found.\n";
        continue;
    }
    $suppId = $supplierIds[$suppIdx];
    $now = date('Y-m-d H:i:s', strtotime('-' . rand(1, 60) . ' days'));

    $stmt = $conn->prepare("INSERT INTO products (supplier_id, category_id, name, slug, description, specifications, main_image, min_order_quantity, min_order_unit, price_range, supply_ability, delivery_time, packaging, port, payment_terms, certifications, is_featured, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?)");
    $featured = $p['featured'];
    $catId = $p['cat'];
    $pName = $p['name'];
    $pSlug = $p['slug'];
    $pDesc = $p['desc'];
    $pSpecs = $p['specs'];
    $pImg = $p['img'];
    $pMoq = $p['moq'];
    $pUnit = $p['unit'];
    $pPrice = $p['price'];
    $pSupply = $p['supply'];
    $pDelivery = $p['delivery'];
    $pPack = $p['packaging'];
    $pPort = $p['port'];
    $pPay = $p['payment'];
    $pCerts = $p['certs'];
    $now2 = $now;
    $stmt->bind_param('iisssssissssssssiss',
        $suppId, $catId, $pName, $pSlug, $pDesc, $pSpecs,
        $pImg, $pMoq, $pUnit, $pPrice, $pSupply,
        $pDelivery, $pPack, $pPort, $pPay, $pCerts,
        $featured, $now, $now2
    );

    if ($stmt->execute()) {
        $prodCount++;
        if ($prodCount % 10 == 0) echo "  Inserted {$prodCount} products...\n";
    } else {
        echo "  ERROR inserting product {$p['name']}: " . $stmt->error . "\n";
    }
    $stmt->close();
}

echo "\nDone! Inserted " . count($supplierIds) . " suppliers and {$prodCount} products.\n";

$conn->close();
