<?php

// Auto-generated by countries:sync on 2026-09-05 16:53:40 -- do not edit by hand.
// Source: mledoze/countries (https://github.com/mledoze/countries) + flagcdn.com.
// Keyed by id so country_id foreign keys in users/buyer_inquiries/contact_submissions
// keep resolving correctly; ids for existing codes are preserved across syncs.
return array (
  1 => 
  array (
    'id' => 1,
    'name' => 'United Arab Emirates',
    'code' => 'AE',
    'phone_code' => '+971',
    'flag' => 'https://flagcdn.com/ae.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  2 => 
  array (
    'id' => 2,
    'name' => 'Pakistan',
    'code' => 'PK',
    'phone_code' => '+92',
    'flag' => 'https://flagcdn.com/pk.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  3 => 
  array (
    'id' => 3,
    'name' => 'India',
    'code' => 'IN',
    'phone_code' => '+91',
    'flag' => 'https://flagcdn.com/in.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  4 => 
  array (
    'id' => 4,
    'name' => 'China',
    'code' => 'CN',
    'phone_code' => '+86',
    'flag' => 'https://flagcdn.com/cn.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  5 => 
  array (
    'id' => 5,
    'name' => 'Bangladesh',
    'code' => 'BD',
    'phone_code' => '+880',
    'flag' => 'https://flagcdn.com/bd.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  6 => 
  array (
    'id' => 6,
    'name' => 'Sri Lanka',
    'code' => 'LK',
    'phone_code' => '+94',
    'flag' => 'https://flagcdn.com/lk.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  7 => 
  array (
    'id' => 7,
    'name' => 'Singapore',
    'code' => 'SG',
    'phone_code' => '+65',
    'flag' => 'https://flagcdn.com/sg.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  8 => 
  array (
    'id' => 8,
    'name' => 'Hong Kong',
    'code' => 'HK',
    'phone_code' => '+852',
    'flag' => 'https://flagcdn.com/hk.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  9 => 
  array (
    'id' => 9,
    'name' => 'Türkiye',
    'code' => 'TR',
    'phone_code' => '+90',
    'flag' => 'https://flagcdn.com/tr.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  10 => 
  array (
    'id' => 10,
    'name' => 'Saudi Arabia',
    'code' => 'SA',
    'phone_code' => '+966',
    'flag' => 'https://flagcdn.com/sa.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  11 => 
  array (
    'id' => 11,
    'name' => 'Malaysia',
    'code' => 'MY',
    'phone_code' => '+60',
    'flag' => 'https://flagcdn.com/my.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  12 => 
  array (
    'id' => 12,
    'name' => 'Indonesia',
    'code' => 'ID',
    'phone_code' => '+62',
    'flag' => 'https://flagcdn.com/id.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  13 => 
  array (
    'id' => 13,
    'name' => 'Vietnam',
    'code' => 'VN',
    'phone_code' => '+84',
    'flag' => 'https://flagcdn.com/vn.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  14 => 
  array (
    'id' => 14,
    'name' => 'Thailand',
    'code' => 'TH',
    'phone_code' => '+66',
    'flag' => 'https://flagcdn.com/th.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  15 => 
  array (
    'id' => 15,
    'name' => 'South Korea',
    'code' => 'KR',
    'phone_code' => '+82',
    'flag' => 'https://flagcdn.com/kr.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  16 => 
  array (
    'id' => 16,
    'name' => 'Japan',
    'code' => 'JP',
    'phone_code' => '+81',
    'flag' => 'https://flagcdn.com/jp.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  17 => 
  array (
    'id' => 17,
    'name' => 'Germany',
    'code' => 'DE',
    'phone_code' => '+49',
    'flag' => 'https://flagcdn.com/de.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  18 => 
  array (
    'id' => 18,
    'name' => 'United Kingdom',
    'code' => 'GB',
    'phone_code' => '+44',
    'flag' => 'https://flagcdn.com/gb.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  19 => 
  array (
    'id' => 19,
    'name' => 'United States',
    'code' => 'US',
    'phone_code' => '+1',
    'flag' => 'https://flagcdn.com/us.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  20 => 
  array (
    'id' => 20,
    'name' => 'Egypt',
    'code' => 'EG',
    'phone_code' => '+20',
    'flag' => 'https://flagcdn.com/eg.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  21 => 
  array (
    'id' => 21,
    'name' => 'Afghanistan',
    'code' => 'AF',
    'phone_code' => '+93',
    'flag' => 'https://flagcdn.com/af.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  22 => 
  array (
    'id' => 22,
    'name' => 'Albania',
    'code' => 'AL',
    'phone_code' => '+355',
    'flag' => 'https://flagcdn.com/al.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  23 => 
  array (
    'id' => 23,
    'name' => 'Algeria',
    'code' => 'DZ',
    'phone_code' => '+213',
    'flag' => 'https://flagcdn.com/dz.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  24 => 
  array (
    'id' => 24,
    'name' => 'Argentina',
    'code' => 'AR',
    'phone_code' => '+54',
    'flag' => 'https://flagcdn.com/ar.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  25 => 
  array (
    'id' => 25,
    'name' => 'Australia',
    'code' => 'AU',
    'phone_code' => '+61',
    'flag' => 'https://flagcdn.com/au.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  26 => 
  array (
    'id' => 26,
    'name' => 'Austria',
    'code' => 'AT',
    'phone_code' => '+43',
    'flag' => 'https://flagcdn.com/at.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  27 => 
  array (
    'id' => 27,
    'name' => 'Bahrain',
    'code' => 'BH',
    'phone_code' => '+973',
    'flag' => 'https://flagcdn.com/bh.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  28 => 
  array (
    'id' => 28,
    'name' => 'Belgium',
    'code' => 'BE',
    'phone_code' => '+32',
    'flag' => 'https://flagcdn.com/be.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  29 => 
  array (
    'id' => 29,
    'name' => 'Bolivia',
    'code' => 'BO',
    'phone_code' => '+591',
    'flag' => 'https://flagcdn.com/bo.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  30 => 
  array (
    'id' => 30,
    'name' => 'Brazil',
    'code' => 'BR',
    'phone_code' => '+55',
    'flag' => 'https://flagcdn.com/br.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  31 => 
  array (
    'id' => 31,
    'name' => 'Brunei',
    'code' => 'BN',
    'phone_code' => '+673',
    'flag' => 'https://flagcdn.com/bn.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  32 => 
  array (
    'id' => 32,
    'name' => 'Bulgaria',
    'code' => 'BG',
    'phone_code' => '+359',
    'flag' => 'https://flagcdn.com/bg.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  33 => 
  array (
    'id' => 33,
    'name' => 'Cambodia',
    'code' => 'KH',
    'phone_code' => '+855',
    'flag' => 'https://flagcdn.com/kh.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  34 => 
  array (
    'id' => 34,
    'name' => 'Cameroon',
    'code' => 'CM',
    'phone_code' => '+237',
    'flag' => 'https://flagcdn.com/cm.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  35 => 
  array (
    'id' => 35,
    'name' => 'Canada',
    'code' => 'CA',
    'phone_code' => '+1',
    'flag' => 'https://flagcdn.com/ca.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  36 => 
  array (
    'id' => 36,
    'name' => 'Chile',
    'code' => 'CL',
    'phone_code' => '+56',
    'flag' => 'https://flagcdn.com/cl.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  37 => 
  array (
    'id' => 37,
    'name' => 'Colombia',
    'code' => 'CO',
    'phone_code' => '+57',
    'flag' => 'https://flagcdn.com/co.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  38 => 
  array (
    'id' => 38,
    'name' => 'Costa Rica',
    'code' => 'CR',
    'phone_code' => '+506',
    'flag' => 'https://flagcdn.com/cr.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  39 => 
  array (
    'id' => 39,
    'name' => 'Croatia',
    'code' => 'HR',
    'phone_code' => '+385',
    'flag' => 'https://flagcdn.com/hr.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  40 => 
  array (
    'id' => 40,
    'name' => 'Cuba',
    'code' => 'CU',
    'phone_code' => '+53',
    'flag' => 'https://flagcdn.com/cu.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  41 => 
  array (
    'id' => 41,
    'name' => 'Cyprus',
    'code' => 'CY',
    'phone_code' => '+357',
    'flag' => 'https://flagcdn.com/cy.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  42 => 
  array (
    'id' => 42,
    'name' => 'Czechia',
    'code' => 'CZ',
    'phone_code' => '+420',
    'flag' => 'https://flagcdn.com/cz.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  43 => 
  array (
    'id' => 43,
    'name' => 'Denmark',
    'code' => 'DK',
    'phone_code' => '+45',
    'flag' => 'https://flagcdn.com/dk.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  44 => 
  array (
    'id' => 44,
    'name' => 'Dominican Republic',
    'code' => 'DO',
    'phone_code' => '+1',
    'flag' => 'https://flagcdn.com/do.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  45 => 
  array (
    'id' => 45,
    'name' => 'Ecuador',
    'code' => 'EC',
    'phone_code' => '+593',
    'flag' => 'https://flagcdn.com/ec.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  46 => 
  array (
    'id' => 46,
    'name' => 'El Salvador',
    'code' => 'SV',
    'phone_code' => '+503',
    'flag' => 'https://flagcdn.com/sv.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  47 => 
  array (
    'id' => 47,
    'name' => 'Ethiopia',
    'code' => 'ET',
    'phone_code' => '+251',
    'flag' => 'https://flagcdn.com/et.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  48 => 
  array (
    'id' => 48,
    'name' => 'Finland',
    'code' => 'FI',
    'phone_code' => '+358',
    'flag' => 'https://flagcdn.com/fi.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  49 => 
  array (
    'id' => 49,
    'name' => 'France',
    'code' => 'FR',
    'phone_code' => '+33',
    'flag' => 'https://flagcdn.com/fr.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  50 => 
  array (
    'id' => 50,
    'name' => 'Ghana',
    'code' => 'GH',
    'phone_code' => '+233',
    'flag' => 'https://flagcdn.com/gh.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  51 => 
  array (
    'id' => 51,
    'name' => 'Greece',
    'code' => 'GR',
    'phone_code' => '+30',
    'flag' => 'https://flagcdn.com/gr.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  52 => 
  array (
    'id' => 52,
    'name' => 'Guatemala',
    'code' => 'GT',
    'phone_code' => '+502',
    'flag' => 'https://flagcdn.com/gt.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  53 => 
  array (
    'id' => 53,
    'name' => 'Honduras',
    'code' => 'HN',
    'phone_code' => '+504',
    'flag' => 'https://flagcdn.com/hn.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  54 => 
  array (
    'id' => 54,
    'name' => 'Hungary',
    'code' => 'HU',
    'phone_code' => '+36',
    'flag' => 'https://flagcdn.com/hu.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  55 => 
  array (
    'id' => 55,
    'name' => 'Iceland',
    'code' => 'IS',
    'phone_code' => '+354',
    'flag' => 'https://flagcdn.com/is.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  56 => 
  array (
    'id' => 56,
    'name' => 'Iran',
    'code' => 'IR',
    'phone_code' => '+98',
    'flag' => 'https://flagcdn.com/ir.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  57 => 
  array (
    'id' => 57,
    'name' => 'Iraq',
    'code' => 'IQ',
    'phone_code' => '+964',
    'flag' => 'https://flagcdn.com/iq.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  58 => 
  array (
    'id' => 58,
    'name' => 'Ireland',
    'code' => 'IE',
    'phone_code' => '+353',
    'flag' => 'https://flagcdn.com/ie.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  59 => 
  array (
    'id' => 59,
    'name' => 'Israel',
    'code' => 'IL',
    'phone_code' => '+972',
    'flag' => 'https://flagcdn.com/il.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  60 => 
  array (
    'id' => 60,
    'name' => 'Italy',
    'code' => 'IT',
    'phone_code' => '+39',
    'flag' => 'https://flagcdn.com/it.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  61 => 
  array (
    'id' => 61,
    'name' => 'Ivory Coast',
    'code' => 'CI',
    'phone_code' => '+225',
    'flag' => 'https://flagcdn.com/ci.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  62 => 
  array (
    'id' => 62,
    'name' => 'Jamaica',
    'code' => 'JM',
    'phone_code' => '+1876',
    'flag' => 'https://flagcdn.com/jm.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  63 => 
  array (
    'id' => 63,
    'name' => 'Jordan',
    'code' => 'JO',
    'phone_code' => '+962',
    'flag' => 'https://flagcdn.com/jo.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  64 => 
  array (
    'id' => 64,
    'name' => 'Kazakhstan',
    'code' => 'KZ',
    'phone_code' => '+7',
    'flag' => 'https://flagcdn.com/kz.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  65 => 
  array (
    'id' => 65,
    'name' => 'Kenya',
    'code' => 'KE',
    'phone_code' => '+254',
    'flag' => 'https://flagcdn.com/ke.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  66 => 
  array (
    'id' => 66,
    'name' => 'Kuwait',
    'code' => 'KW',
    'phone_code' => '+965',
    'flag' => 'https://flagcdn.com/kw.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  67 => 
  array (
    'id' => 67,
    'name' => 'Laos',
    'code' => 'LA',
    'phone_code' => '+856',
    'flag' => 'https://flagcdn.com/la.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  68 => 
  array (
    'id' => 68,
    'name' => 'Latvia',
    'code' => 'LV',
    'phone_code' => '+371',
    'flag' => 'https://flagcdn.com/lv.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  69 => 
  array (
    'id' => 69,
    'name' => 'Lebanon',
    'code' => 'LB',
    'phone_code' => '+961',
    'flag' => 'https://flagcdn.com/lb.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  70 => 
  array (
    'id' => 70,
    'name' => 'Libya',
    'code' => 'LY',
    'phone_code' => '+218',
    'flag' => 'https://flagcdn.com/ly.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  71 => 
  array (
    'id' => 71,
    'name' => 'Lithuania',
    'code' => 'LT',
    'phone_code' => '+370',
    'flag' => 'https://flagcdn.com/lt.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  72 => 
  array (
    'id' => 72,
    'name' => 'Luxembourg',
    'code' => 'LU',
    'phone_code' => '+352',
    'flag' => 'https://flagcdn.com/lu.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  73 => 
  array (
    'id' => 73,
    'name' => 'Madagascar',
    'code' => 'MG',
    'phone_code' => '+261',
    'flag' => 'https://flagcdn.com/mg.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  74 => 
  array (
    'id' => 74,
    'name' => 'Maldives',
    'code' => 'MV',
    'phone_code' => '+960',
    'flag' => 'https://flagcdn.com/mv.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  75 => 
  array (
    'id' => 75,
    'name' => 'Mexico',
    'code' => 'MX',
    'phone_code' => '+52',
    'flag' => 'https://flagcdn.com/mx.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  76 => 
  array (
    'id' => 76,
    'name' => 'Mongolia',
    'code' => 'MN',
    'phone_code' => '+976',
    'flag' => 'https://flagcdn.com/mn.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  77 => 
  array (
    'id' => 77,
    'name' => 'Morocco',
    'code' => 'MA',
    'phone_code' => '+212',
    'flag' => 'https://flagcdn.com/ma.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  78 => 
  array (
    'id' => 78,
    'name' => 'Mozambique',
    'code' => 'MZ',
    'phone_code' => '+258',
    'flag' => 'https://flagcdn.com/mz.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  79 => 
  array (
    'id' => 79,
    'name' => 'Myanmar',
    'code' => 'MM',
    'phone_code' => '+95',
    'flag' => 'https://flagcdn.com/mm.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  80 => 
  array (
    'id' => 80,
    'name' => 'Nepal',
    'code' => 'NP',
    'phone_code' => '+977',
    'flag' => 'https://flagcdn.com/np.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  81 => 
  array (
    'id' => 81,
    'name' => 'Netherlands',
    'code' => 'NL',
    'phone_code' => '+31',
    'flag' => 'https://flagcdn.com/nl.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  82 => 
  array (
    'id' => 82,
    'name' => 'New Zealand',
    'code' => 'NZ',
    'phone_code' => '+64',
    'flag' => 'https://flagcdn.com/nz.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  83 => 
  array (
    'id' => 83,
    'name' => 'Nicaragua',
    'code' => 'NI',
    'phone_code' => '+505',
    'flag' => 'https://flagcdn.com/ni.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  84 => 
  array (
    'id' => 84,
    'name' => 'Nigeria',
    'code' => 'NG',
    'phone_code' => '+234',
    'flag' => 'https://flagcdn.com/ng.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  85 => 
  array (
    'id' => 85,
    'name' => 'North Korea',
    'code' => 'KP',
    'phone_code' => '+850',
    'flag' => 'https://flagcdn.com/kp.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  86 => 
  array (
    'id' => 86,
    'name' => 'Norway',
    'code' => 'NO',
    'phone_code' => '+47',
    'flag' => 'https://flagcdn.com/no.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  87 => 
  array (
    'id' => 87,
    'name' => 'Oman',
    'code' => 'OM',
    'phone_code' => '+968',
    'flag' => 'https://flagcdn.com/om.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  88 => 
  array (
    'id' => 88,
    'name' => 'Palestine',
    'code' => 'PS',
    'phone_code' => '+970',
    'flag' => 'https://flagcdn.com/ps.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  89 => 
  array (
    'id' => 89,
    'name' => 'Panama',
    'code' => 'PA',
    'phone_code' => '+507',
    'flag' => 'https://flagcdn.com/pa.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  90 => 
  array (
    'id' => 90,
    'name' => 'Paraguay',
    'code' => 'PY',
    'phone_code' => '+595',
    'flag' => 'https://flagcdn.com/py.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  91 => 
  array (
    'id' => 91,
    'name' => 'Peru',
    'code' => 'PE',
    'phone_code' => '+51',
    'flag' => 'https://flagcdn.com/pe.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  92 => 
  array (
    'id' => 92,
    'name' => 'Philippines',
    'code' => 'PH',
    'phone_code' => '+63',
    'flag' => 'https://flagcdn.com/ph.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  93 => 
  array (
    'id' => 93,
    'name' => 'Poland',
    'code' => 'PL',
    'phone_code' => '+48',
    'flag' => 'https://flagcdn.com/pl.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  94 => 
  array (
    'id' => 94,
    'name' => 'Portugal',
    'code' => 'PT',
    'phone_code' => '+351',
    'flag' => 'https://flagcdn.com/pt.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  95 => 
  array (
    'id' => 95,
    'name' => 'Qatar',
    'code' => 'QA',
    'phone_code' => '+974',
    'flag' => 'https://flagcdn.com/qa.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  96 => 
  array (
    'id' => 96,
    'name' => 'Romania',
    'code' => 'RO',
    'phone_code' => '+40',
    'flag' => 'https://flagcdn.com/ro.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  97 => 
  array (
    'id' => 97,
    'name' => 'Russia',
    'code' => 'RU',
    'phone_code' => '+7',
    'flag' => 'https://flagcdn.com/ru.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  98 => 
  array (
    'id' => 98,
    'name' => 'Rwanda',
    'code' => 'RW',
    'phone_code' => '+250',
    'flag' => 'https://flagcdn.com/rw.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  99 => 
  array (
    'id' => 99,
    'name' => 'Senegal',
    'code' => 'SN',
    'phone_code' => '+221',
    'flag' => 'https://flagcdn.com/sn.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  100 => 
  array (
    'id' => 100,
    'name' => 'Serbia',
    'code' => 'RS',
    'phone_code' => '+381',
    'flag' => 'https://flagcdn.com/rs.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  101 => 
  array (
    'id' => 101,
    'name' => 'Slovakia',
    'code' => 'SK',
    'phone_code' => '+421',
    'flag' => 'https://flagcdn.com/sk.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  102 => 
  array (
    'id' => 102,
    'name' => 'Slovenia',
    'code' => 'SI',
    'phone_code' => '+386',
    'flag' => 'https://flagcdn.com/si.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  103 => 
  array (
    'id' => 103,
    'name' => 'Somalia',
    'code' => 'SO',
    'phone_code' => '+252',
    'flag' => 'https://flagcdn.com/so.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  104 => 
  array (
    'id' => 104,
    'name' => 'South Africa',
    'code' => 'ZA',
    'phone_code' => '+27',
    'flag' => 'https://flagcdn.com/za.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  105 => 
  array (
    'id' => 105,
    'name' => 'Spain',
    'code' => 'ES',
    'phone_code' => '+34',
    'flag' => 'https://flagcdn.com/es.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  106 => 
  array (
    'id' => 106,
    'name' => 'Sudan',
    'code' => 'SD',
    'phone_code' => '+249',
    'flag' => 'https://flagcdn.com/sd.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  107 => 
  array (
    'id' => 107,
    'name' => 'Sweden',
    'code' => 'SE',
    'phone_code' => '+46',
    'flag' => 'https://flagcdn.com/se.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  108 => 
  array (
    'id' => 108,
    'name' => 'Switzerland',
    'code' => 'CH',
    'phone_code' => '+41',
    'flag' => 'https://flagcdn.com/ch.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  109 => 
  array (
    'id' => 109,
    'name' => 'Syria',
    'code' => 'SY',
    'phone_code' => '+963',
    'flag' => 'https://flagcdn.com/sy.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  110 => 
  array (
    'id' => 110,
    'name' => 'Taiwan',
    'code' => 'TW',
    'phone_code' => '+886',
    'flag' => 'https://flagcdn.com/tw.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  111 => 
  array (
    'id' => 111,
    'name' => 'Tanzania',
    'code' => 'TZ',
    'phone_code' => '+255',
    'flag' => 'https://flagcdn.com/tz.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  112 => 
  array (
    'id' => 112,
    'name' => 'Trinidad and Tobago',
    'code' => 'TT',
    'phone_code' => '+1868',
    'flag' => 'https://flagcdn.com/tt.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  113 => 
  array (
    'id' => 113,
    'name' => 'Tunisia',
    'code' => 'TN',
    'phone_code' => '+216',
    'flag' => 'https://flagcdn.com/tn.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  114 => 
  array (
    'id' => 114,
    'name' => 'Turkmenistan',
    'code' => 'TM',
    'phone_code' => '+993',
    'flag' => 'https://flagcdn.com/tm.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  115 => 
  array (
    'id' => 115,
    'name' => 'Uganda',
    'code' => 'UG',
    'phone_code' => '+256',
    'flag' => 'https://flagcdn.com/ug.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  116 => 
  array (
    'id' => 116,
    'name' => 'Ukraine',
    'code' => 'UA',
    'phone_code' => '+380',
    'flag' => 'https://flagcdn.com/ua.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  117 => 
  array (
    'id' => 117,
    'name' => 'Uruguay',
    'code' => 'UY',
    'phone_code' => '+598',
    'flag' => 'https://flagcdn.com/uy.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  118 => 
  array (
    'id' => 118,
    'name' => 'Uzbekistan',
    'code' => 'UZ',
    'phone_code' => '+998',
    'flag' => 'https://flagcdn.com/uz.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  119 => 
  array (
    'id' => 119,
    'name' => 'Venezuela',
    'code' => 'VE',
    'phone_code' => '+58',
    'flag' => 'https://flagcdn.com/ve.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  120 => 
  array (
    'id' => 120,
    'name' => 'Yemen',
    'code' => 'YE',
    'phone_code' => '+967',
    'flag' => 'https://flagcdn.com/ye.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  121 => 
  array (
    'id' => 121,
    'name' => 'Zambia',
    'code' => 'ZM',
    'phone_code' => '+260',
    'flag' => 'https://flagcdn.com/zm.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  122 => 
  array (
    'id' => 122,
    'name' => 'Zimbabwe',
    'code' => 'ZW',
    'phone_code' => '+263',
    'flag' => 'https://flagcdn.com/zw.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  123 => 
  array (
    'id' => 123,
    'name' => 'Aruba',
    'code' => 'AW',
    'phone_code' => '+297',
    'flag' => 'https://flagcdn.com/aw.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  124 => 
  array (
    'id' => 124,
    'name' => 'Angola',
    'code' => 'AO',
    'phone_code' => '+244',
    'flag' => 'https://flagcdn.com/ao.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  125 => 
  array (
    'id' => 125,
    'name' => 'Anguilla',
    'code' => 'AI',
    'phone_code' => '+1264',
    'flag' => 'https://flagcdn.com/ai.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  126 => 
  array (
    'id' => 126,
    'name' => 'Åland Islands',
    'code' => 'AX',
    'phone_code' => '+35818',
    'flag' => 'https://flagcdn.com/ax.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  127 => 
  array (
    'id' => 127,
    'name' => 'Andorra',
    'code' => 'AD',
    'phone_code' => '+376',
    'flag' => 'https://flagcdn.com/ad.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  128 => 
  array (
    'id' => 128,
    'name' => 'Armenia',
    'code' => 'AM',
    'phone_code' => '+374',
    'flag' => 'https://flagcdn.com/am.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  129 => 
  array (
    'id' => 129,
    'name' => 'American Samoa',
    'code' => 'AS',
    'phone_code' => '+1684',
    'flag' => 'https://flagcdn.com/as.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  130 => 
  array (
    'id' => 130,
    'name' => 'Antarctica',
    'code' => 'AQ',
    'phone_code' => '',
    'flag' => 'https://flagcdn.com/aq.svg',
    'region' => 'Antarctic',
    'status' => 'active',
  ),
  131 => 
  array (
    'id' => 131,
    'name' => 'French Southern and Antarctic Lands',
    'code' => 'TF',
    'phone_code' => '+262',
    'flag' => 'https://flagcdn.com/tf.svg',
    'region' => 'Antarctic',
    'status' => 'active',
  ),
  132 => 
  array (
    'id' => 132,
    'name' => 'Antigua and Barbuda',
    'code' => 'AG',
    'phone_code' => '+1268',
    'flag' => 'https://flagcdn.com/ag.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  133 => 
  array (
    'id' => 133,
    'name' => 'Azerbaijan',
    'code' => 'AZ',
    'phone_code' => '+994',
    'flag' => 'https://flagcdn.com/az.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  134 => 
  array (
    'id' => 134,
    'name' => 'Burundi',
    'code' => 'BI',
    'phone_code' => '+257',
    'flag' => 'https://flagcdn.com/bi.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  135 => 
  array (
    'id' => 135,
    'name' => 'Benin',
    'code' => 'BJ',
    'phone_code' => '+229',
    'flag' => 'https://flagcdn.com/bj.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  136 => 
  array (
    'id' => 136,
    'name' => 'Burkina Faso',
    'code' => 'BF',
    'phone_code' => '+226',
    'flag' => 'https://flagcdn.com/bf.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  137 => 
  array (
    'id' => 137,
    'name' => 'Bahamas',
    'code' => 'BS',
    'phone_code' => '+1242',
    'flag' => 'https://flagcdn.com/bs.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  138 => 
  array (
    'id' => 138,
    'name' => 'Bosnia and Herzegovina',
    'code' => 'BA',
    'phone_code' => '+387',
    'flag' => 'https://flagcdn.com/ba.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  139 => 
  array (
    'id' => 139,
    'name' => 'Saint Barthélemy',
    'code' => 'BL',
    'phone_code' => '+590',
    'flag' => 'https://flagcdn.com/bl.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  140 => 
  array (
    'id' => 140,
    'name' => 'Saint Helena, Ascension and Tristan da Cunha',
    'code' => 'SH',
    'phone_code' => '+2',
    'flag' => 'https://flagcdn.com/sh.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  141 => 
  array (
    'id' => 141,
    'name' => 'Belarus',
    'code' => 'BY',
    'phone_code' => '+375',
    'flag' => 'https://flagcdn.com/by.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  142 => 
  array (
    'id' => 142,
    'name' => 'Belize',
    'code' => 'BZ',
    'phone_code' => '+501',
    'flag' => 'https://flagcdn.com/bz.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  143 => 
  array (
    'id' => 143,
    'name' => 'Bermuda',
    'code' => 'BM',
    'phone_code' => '+1441',
    'flag' => 'https://flagcdn.com/bm.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  144 => 
  array (
    'id' => 144,
    'name' => 'Caribbean Netherlands',
    'code' => 'BQ',
    'phone_code' => '+599',
    'flag' => 'https://flagcdn.com/bq.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  145 => 
  array (
    'id' => 145,
    'name' => 'Barbados',
    'code' => 'BB',
    'phone_code' => '+1246',
    'flag' => 'https://flagcdn.com/bb.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  146 => 
  array (
    'id' => 146,
    'name' => 'Bhutan',
    'code' => 'BT',
    'phone_code' => '+975',
    'flag' => 'https://flagcdn.com/bt.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  147 => 
  array (
    'id' => 147,
    'name' => 'Bouvet Island',
    'code' => 'BV',
    'phone_code' => '+47',
    'flag' => 'https://flagcdn.com/bv.svg',
    'region' => 'Antarctic',
    'status' => 'active',
  ),
  148 => 
  array (
    'id' => 148,
    'name' => 'Botswana',
    'code' => 'BW',
    'phone_code' => '+267',
    'flag' => 'https://flagcdn.com/bw.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  149 => 
  array (
    'id' => 149,
    'name' => 'Central African Republic',
    'code' => 'CF',
    'phone_code' => '+236',
    'flag' => 'https://flagcdn.com/cf.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  150 => 
  array (
    'id' => 150,
    'name' => 'Cocos (Keeling) Islands',
    'code' => 'CC',
    'phone_code' => '+61',
    'flag' => 'https://flagcdn.com/cc.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  151 => 
  array (
    'id' => 151,
    'name' => 'DR Congo',
    'code' => 'CD',
    'phone_code' => '+243',
    'flag' => 'https://flagcdn.com/cd.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  152 => 
  array (
    'id' => 152,
    'name' => 'Congo',
    'code' => 'CG',
    'phone_code' => '+242',
    'flag' => 'https://flagcdn.com/cg.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  153 => 
  array (
    'id' => 153,
    'name' => 'Cook Islands',
    'code' => 'CK',
    'phone_code' => '+682',
    'flag' => 'https://flagcdn.com/ck.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  154 => 
  array (
    'id' => 154,
    'name' => 'Comoros',
    'code' => 'KM',
    'phone_code' => '+269',
    'flag' => 'https://flagcdn.com/km.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  155 => 
  array (
    'id' => 155,
    'name' => 'Cape Verde',
    'code' => 'CV',
    'phone_code' => '+238',
    'flag' => 'https://flagcdn.com/cv.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  156 => 
  array (
    'id' => 156,
    'name' => 'Curaçao',
    'code' => 'CW',
    'phone_code' => '+599',
    'flag' => 'https://flagcdn.com/cw.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  157 => 
  array (
    'id' => 157,
    'name' => 'Christmas Island',
    'code' => 'CX',
    'phone_code' => '+61',
    'flag' => 'https://flagcdn.com/cx.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  158 => 
  array (
    'id' => 158,
    'name' => 'Cayman Islands',
    'code' => 'KY',
    'phone_code' => '+1345',
    'flag' => 'https://flagcdn.com/ky.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  159 => 
  array (
    'id' => 159,
    'name' => 'Djibouti',
    'code' => 'DJ',
    'phone_code' => '+253',
    'flag' => 'https://flagcdn.com/dj.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  160 => 
  array (
    'id' => 160,
    'name' => 'Dominica',
    'code' => 'DM',
    'phone_code' => '+1767',
    'flag' => 'https://flagcdn.com/dm.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  161 => 
  array (
    'id' => 161,
    'name' => 'Eritrea',
    'code' => 'ER',
    'phone_code' => '+291',
    'flag' => 'https://flagcdn.com/er.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  162 => 
  array (
    'id' => 162,
    'name' => 'Western Sahara',
    'code' => 'EH',
    'phone_code' => '+2',
    'flag' => 'https://flagcdn.com/eh.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  163 => 
  array (
    'id' => 163,
    'name' => 'Estonia',
    'code' => 'EE',
    'phone_code' => '+372',
    'flag' => 'https://flagcdn.com/ee.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  164 => 
  array (
    'id' => 164,
    'name' => 'Fiji',
    'code' => 'FJ',
    'phone_code' => '+679',
    'flag' => 'https://flagcdn.com/fj.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  165 => 
  array (
    'id' => 165,
    'name' => 'Falkland Islands',
    'code' => 'FK',
    'phone_code' => '+500',
    'flag' => 'https://flagcdn.com/fk.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  166 => 
  array (
    'id' => 166,
    'name' => 'Faroe Islands',
    'code' => 'FO',
    'phone_code' => '+298',
    'flag' => 'https://flagcdn.com/fo.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  167 => 
  array (
    'id' => 167,
    'name' => 'Micronesia',
    'code' => 'FM',
    'phone_code' => '+691',
    'flag' => 'https://flagcdn.com/fm.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  168 => 
  array (
    'id' => 168,
    'name' => 'Gabon',
    'code' => 'GA',
    'phone_code' => '+241',
    'flag' => 'https://flagcdn.com/ga.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  169 => 
  array (
    'id' => 169,
    'name' => 'Georgia',
    'code' => 'GE',
    'phone_code' => '+995',
    'flag' => 'https://flagcdn.com/ge.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  170 => 
  array (
    'id' => 170,
    'name' => 'Guernsey',
    'code' => 'GG',
    'phone_code' => '+44',
    'flag' => 'https://flagcdn.com/gg.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  171 => 
  array (
    'id' => 171,
    'name' => 'Gibraltar',
    'code' => 'GI',
    'phone_code' => '+350',
    'flag' => 'https://flagcdn.com/gi.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  172 => 
  array (
    'id' => 172,
    'name' => 'Guinea',
    'code' => 'GN',
    'phone_code' => '+224',
    'flag' => 'https://flagcdn.com/gn.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  173 => 
  array (
    'id' => 173,
    'name' => 'Guadeloupe',
    'code' => 'GP',
    'phone_code' => '+590',
    'flag' => 'https://flagcdn.com/gp.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  174 => 
  array (
    'id' => 174,
    'name' => 'Gambia',
    'code' => 'GM',
    'phone_code' => '+220',
    'flag' => 'https://flagcdn.com/gm.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  175 => 
  array (
    'id' => 175,
    'name' => 'Guinea-Bissau',
    'code' => 'GW',
    'phone_code' => '+245',
    'flag' => 'https://flagcdn.com/gw.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  176 => 
  array (
    'id' => 176,
    'name' => 'Equatorial Guinea',
    'code' => 'GQ',
    'phone_code' => '+240',
    'flag' => 'https://flagcdn.com/gq.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  177 => 
  array (
    'id' => 177,
    'name' => 'Grenada',
    'code' => 'GD',
    'phone_code' => '+1473',
    'flag' => 'https://flagcdn.com/gd.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  178 => 
  array (
    'id' => 178,
    'name' => 'Greenland',
    'code' => 'GL',
    'phone_code' => '+299',
    'flag' => 'https://flagcdn.com/gl.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  179 => 
  array (
    'id' => 179,
    'name' => 'French Guiana',
    'code' => 'GF',
    'phone_code' => '+594',
    'flag' => 'https://flagcdn.com/gf.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  180 => 
  array (
    'id' => 180,
    'name' => 'Guam',
    'code' => 'GU',
    'phone_code' => '+1671',
    'flag' => 'https://flagcdn.com/gu.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  181 => 
  array (
    'id' => 181,
    'name' => 'Guyana',
    'code' => 'GY',
    'phone_code' => '+592',
    'flag' => 'https://flagcdn.com/gy.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  182 => 
  array (
    'id' => 182,
    'name' => 'Heard Island and McDonald Islands',
    'code' => 'HM',
    'phone_code' => '',
    'flag' => 'https://flagcdn.com/hm.svg',
    'region' => 'Antarctic',
    'status' => 'active',
  ),
  183 => 
  array (
    'id' => 183,
    'name' => 'Haiti',
    'code' => 'HT',
    'phone_code' => '+509',
    'flag' => 'https://flagcdn.com/ht.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  184 => 
  array (
    'id' => 184,
    'name' => 'Isle of Man',
    'code' => 'IM',
    'phone_code' => '+44',
    'flag' => 'https://flagcdn.com/im.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  185 => 
  array (
    'id' => 185,
    'name' => 'British Indian Ocean Territory',
    'code' => 'IO',
    'phone_code' => '+246',
    'flag' => 'https://flagcdn.com/io.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  186 => 
  array (
    'id' => 186,
    'name' => 'Jersey',
    'code' => 'JE',
    'phone_code' => '+44',
    'flag' => 'https://flagcdn.com/je.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  187 => 
  array (
    'id' => 187,
    'name' => 'Kyrgyzstan',
    'code' => 'KG',
    'phone_code' => '+996',
    'flag' => 'https://flagcdn.com/kg.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  188 => 
  array (
    'id' => 188,
    'name' => 'Kiribati',
    'code' => 'KI',
    'phone_code' => '+686',
    'flag' => 'https://flagcdn.com/ki.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  189 => 
  array (
    'id' => 189,
    'name' => 'Saint Kitts and Nevis',
    'code' => 'KN',
    'phone_code' => '+1869',
    'flag' => 'https://flagcdn.com/kn.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  190 => 
  array (
    'id' => 190,
    'name' => 'Kosovo',
    'code' => 'XK',
    'phone_code' => '+383',
    'flag' => 'https://flagcdn.com/xk.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  191 => 
  array (
    'id' => 191,
    'name' => 'Liberia',
    'code' => 'LR',
    'phone_code' => '+231',
    'flag' => 'https://flagcdn.com/lr.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  192 => 
  array (
    'id' => 192,
    'name' => 'Saint Lucia',
    'code' => 'LC',
    'phone_code' => '+1758',
    'flag' => 'https://flagcdn.com/lc.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  193 => 
  array (
    'id' => 193,
    'name' => 'Liechtenstein',
    'code' => 'LI',
    'phone_code' => '+423',
    'flag' => 'https://flagcdn.com/li.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  194 => 
  array (
    'id' => 194,
    'name' => 'Lesotho',
    'code' => 'LS',
    'phone_code' => '+266',
    'flag' => 'https://flagcdn.com/ls.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  195 => 
  array (
    'id' => 195,
    'name' => 'Macau',
    'code' => 'MO',
    'phone_code' => '+853',
    'flag' => 'https://flagcdn.com/mo.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  196 => 
  array (
    'id' => 196,
    'name' => 'Saint Martin',
    'code' => 'MF',
    'phone_code' => '+590',
    'flag' => 'https://flagcdn.com/mf.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  197 => 
  array (
    'id' => 197,
    'name' => 'Monaco',
    'code' => 'MC',
    'phone_code' => '+377',
    'flag' => 'https://flagcdn.com/mc.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  198 => 
  array (
    'id' => 198,
    'name' => 'Moldova',
    'code' => 'MD',
    'phone_code' => '+373',
    'flag' => 'https://flagcdn.com/md.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  199 => 
  array (
    'id' => 199,
    'name' => 'Marshall Islands',
    'code' => 'MH',
    'phone_code' => '+692',
    'flag' => 'https://flagcdn.com/mh.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  200 => 
  array (
    'id' => 200,
    'name' => 'North Macedonia',
    'code' => 'MK',
    'phone_code' => '+389',
    'flag' => 'https://flagcdn.com/mk.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  201 => 
  array (
    'id' => 201,
    'name' => 'Mali',
    'code' => 'ML',
    'phone_code' => '+223',
    'flag' => 'https://flagcdn.com/ml.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  202 => 
  array (
    'id' => 202,
    'name' => 'Malta',
    'code' => 'MT',
    'phone_code' => '+356',
    'flag' => 'https://flagcdn.com/mt.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  203 => 
  array (
    'id' => 203,
    'name' => 'Montenegro',
    'code' => 'ME',
    'phone_code' => '+382',
    'flag' => 'https://flagcdn.com/me.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  204 => 
  array (
    'id' => 204,
    'name' => 'Northern Mariana Islands',
    'code' => 'MP',
    'phone_code' => '+1670',
    'flag' => 'https://flagcdn.com/mp.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  205 => 
  array (
    'id' => 205,
    'name' => 'Mauritania',
    'code' => 'MR',
    'phone_code' => '+222',
    'flag' => 'https://flagcdn.com/mr.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  206 => 
  array (
    'id' => 206,
    'name' => 'Montserrat',
    'code' => 'MS',
    'phone_code' => '+1664',
    'flag' => 'https://flagcdn.com/ms.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  207 => 
  array (
    'id' => 207,
    'name' => 'Martinique',
    'code' => 'MQ',
    'phone_code' => '+596',
    'flag' => 'https://flagcdn.com/mq.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  208 => 
  array (
    'id' => 208,
    'name' => 'Mauritius',
    'code' => 'MU',
    'phone_code' => '+230',
    'flag' => 'https://flagcdn.com/mu.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  209 => 
  array (
    'id' => 209,
    'name' => 'Malawi',
    'code' => 'MW',
    'phone_code' => '+265',
    'flag' => 'https://flagcdn.com/mw.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  210 => 
  array (
    'id' => 210,
    'name' => 'Mayotte',
    'code' => 'YT',
    'phone_code' => '+262',
    'flag' => 'https://flagcdn.com/yt.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  211 => 
  array (
    'id' => 211,
    'name' => 'Namibia',
    'code' => 'NA',
    'phone_code' => '+264',
    'flag' => 'https://flagcdn.com/na.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  212 => 
  array (
    'id' => 212,
    'name' => 'New Caledonia',
    'code' => 'NC',
    'phone_code' => '+687',
    'flag' => 'https://flagcdn.com/nc.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  213 => 
  array (
    'id' => 213,
    'name' => 'Niger',
    'code' => 'NE',
    'phone_code' => '+227',
    'flag' => 'https://flagcdn.com/ne.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  214 => 
  array (
    'id' => 214,
    'name' => 'Norfolk Island',
    'code' => 'NF',
    'phone_code' => '+672',
    'flag' => 'https://flagcdn.com/nf.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  215 => 
  array (
    'id' => 215,
    'name' => 'Niue',
    'code' => 'NU',
    'phone_code' => '+683',
    'flag' => 'https://flagcdn.com/nu.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  216 => 
  array (
    'id' => 216,
    'name' => 'Nauru',
    'code' => 'NR',
    'phone_code' => '+674',
    'flag' => 'https://flagcdn.com/nr.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  217 => 
  array (
    'id' => 217,
    'name' => 'Pitcairn Islands',
    'code' => 'PN',
    'phone_code' => '+64',
    'flag' => 'https://flagcdn.com/pn.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  218 => 
  array (
    'id' => 218,
    'name' => 'Palau',
    'code' => 'PW',
    'phone_code' => '+680',
    'flag' => 'https://flagcdn.com/pw.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  219 => 
  array (
    'id' => 219,
    'name' => 'Papua New Guinea',
    'code' => 'PG',
    'phone_code' => '+675',
    'flag' => 'https://flagcdn.com/pg.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  220 => 
  array (
    'id' => 220,
    'name' => 'Puerto Rico',
    'code' => 'PR',
    'phone_code' => '+1',
    'flag' => 'https://flagcdn.com/pr.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  221 => 
  array (
    'id' => 221,
    'name' => 'French Polynesia',
    'code' => 'PF',
    'phone_code' => '+689',
    'flag' => 'https://flagcdn.com/pf.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  222 => 
  array (
    'id' => 222,
    'name' => 'Réunion',
    'code' => 'RE',
    'phone_code' => '+262',
    'flag' => 'https://flagcdn.com/re.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  223 => 
  array (
    'id' => 223,
    'name' => 'South Georgia',
    'code' => 'GS',
    'phone_code' => '+500',
    'flag' => 'https://flagcdn.com/gs.svg',
    'region' => 'Antarctic',
    'status' => 'active',
  ),
  224 => 
  array (
    'id' => 224,
    'name' => 'Svalbard and Jan Mayen',
    'code' => 'SJ',
    'phone_code' => '+4779',
    'flag' => 'https://flagcdn.com/sj.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  225 => 
  array (
    'id' => 225,
    'name' => 'Solomon Islands',
    'code' => 'SB',
    'phone_code' => '+677',
    'flag' => 'https://flagcdn.com/sb.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  226 => 
  array (
    'id' => 226,
    'name' => 'Sierra Leone',
    'code' => 'SL',
    'phone_code' => '+232',
    'flag' => 'https://flagcdn.com/sl.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  227 => 
  array (
    'id' => 227,
    'name' => 'San Marino',
    'code' => 'SM',
    'phone_code' => '+378',
    'flag' => 'https://flagcdn.com/sm.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  228 => 
  array (
    'id' => 228,
    'name' => 'Saint Pierre and Miquelon',
    'code' => 'PM',
    'phone_code' => '+508',
    'flag' => 'https://flagcdn.com/pm.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  229 => 
  array (
    'id' => 229,
    'name' => 'South Sudan',
    'code' => 'SS',
    'phone_code' => '+211',
    'flag' => 'https://flagcdn.com/ss.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  230 => 
  array (
    'id' => 230,
    'name' => 'São Tomé and Príncipe',
    'code' => 'ST',
    'phone_code' => '+239',
    'flag' => 'https://flagcdn.com/st.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  231 => 
  array (
    'id' => 231,
    'name' => 'Suriname',
    'code' => 'SR',
    'phone_code' => '+597',
    'flag' => 'https://flagcdn.com/sr.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  232 => 
  array (
    'id' => 232,
    'name' => 'Eswatini',
    'code' => 'SZ',
    'phone_code' => '+268',
    'flag' => 'https://flagcdn.com/sz.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  233 => 
  array (
    'id' => 233,
    'name' => 'Sint Maarten',
    'code' => 'SX',
    'phone_code' => '+1721',
    'flag' => 'https://flagcdn.com/sx.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  234 => 
  array (
    'id' => 234,
    'name' => 'Seychelles',
    'code' => 'SC',
    'phone_code' => '+248',
    'flag' => 'https://flagcdn.com/sc.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  235 => 
  array (
    'id' => 235,
    'name' => 'Turks and Caicos Islands',
    'code' => 'TC',
    'phone_code' => '+1649',
    'flag' => 'https://flagcdn.com/tc.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  236 => 
  array (
    'id' => 236,
    'name' => 'Chad',
    'code' => 'TD',
    'phone_code' => '+235',
    'flag' => 'https://flagcdn.com/td.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  237 => 
  array (
    'id' => 237,
    'name' => 'Togo',
    'code' => 'TG',
    'phone_code' => '+228',
    'flag' => 'https://flagcdn.com/tg.svg',
    'region' => 'Africa',
    'status' => 'active',
  ),
  238 => 
  array (
    'id' => 238,
    'name' => 'Tajikistan',
    'code' => 'TJ',
    'phone_code' => '+992',
    'flag' => 'https://flagcdn.com/tj.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  239 => 
  array (
    'id' => 239,
    'name' => 'Tokelau',
    'code' => 'TK',
    'phone_code' => '+690',
    'flag' => 'https://flagcdn.com/tk.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  240 => 
  array (
    'id' => 240,
    'name' => 'Timor-Leste',
    'code' => 'TL',
    'phone_code' => '+670',
    'flag' => 'https://flagcdn.com/tl.svg',
    'region' => 'Asia',
    'status' => 'active',
  ),
  241 => 
  array (
    'id' => 241,
    'name' => 'Tonga',
    'code' => 'TO',
    'phone_code' => '+676',
    'flag' => 'https://flagcdn.com/to.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  242 => 
  array (
    'id' => 242,
    'name' => 'Tuvalu',
    'code' => 'TV',
    'phone_code' => '+688',
    'flag' => 'https://flagcdn.com/tv.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  243 => 
  array (
    'id' => 243,
    'name' => 'United States Minor Outlying Islands',
    'code' => 'UM',
    'phone_code' => '+268',
    'flag' => 'https://flagcdn.com/um.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  244 => 
  array (
    'id' => 244,
    'name' => 'Vatican City',
    'code' => 'VA',
    'phone_code' => '+3',
    'flag' => 'https://flagcdn.com/va.svg',
    'region' => 'Europe',
    'status' => 'active',
  ),
  245 => 
  array (
    'id' => 245,
    'name' => 'Saint Vincent and the Grenadines',
    'code' => 'VC',
    'phone_code' => '+1784',
    'flag' => 'https://flagcdn.com/vc.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  246 => 
  array (
    'id' => 246,
    'name' => 'British Virgin Islands',
    'code' => 'VG',
    'phone_code' => '+1284',
    'flag' => 'https://flagcdn.com/vg.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  247 => 
  array (
    'id' => 247,
    'name' => 'United States Virgin Islands',
    'code' => 'VI',
    'phone_code' => '+1340',
    'flag' => 'https://flagcdn.com/vi.svg',
    'region' => 'Americas',
    'status' => 'active',
  ),
  248 => 
  array (
    'id' => 248,
    'name' => 'Vanuatu',
    'code' => 'VU',
    'phone_code' => '+678',
    'flag' => 'https://flagcdn.com/vu.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  249 => 
  array (
    'id' => 249,
    'name' => 'Wallis and Futuna',
    'code' => 'WF',
    'phone_code' => '+681',
    'flag' => 'https://flagcdn.com/wf.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
  250 => 
  array (
    'id' => 250,
    'name' => 'Samoa',
    'code' => 'WS',
    'phone_code' => '+685',
    'flag' => 'https://flagcdn.com/ws.svg',
    'region' => 'Oceania',
    'status' => 'active',
  ),
);
