<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DataSeeder extends Seeder
{
    public function run()
    {
        $this->seedCountries();
        $this->seedCategories();
        $this->seedSuppliers();
        $this->seedProducts();
        $this->seedBuyerInquiries();
    }

    private function seedCountries()
    {
        $countries = [
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'phone_code' => '+971', 'flag' => 'uae.svg', 'region' => 'Middle East'],
            ['name' => 'Pakistan', 'code' => 'PK', 'phone_code' => '+92', 'flag' => 'pakistan.svg', 'region' => 'South Asia'],
            ['name' => 'India', 'code' => 'IN', 'phone_code' => '+91', 'flag' => 'india.svg', 'region' => 'South Asia'],
            ['name' => 'China', 'code' => 'CN', 'phone_code' => '+86', 'flag' => 'china.svg', 'region' => 'East Asia'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'phone_code' => '+880', 'flag' => 'bangladesh.svg', 'region' => 'South Asia'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'phone_code' => '+94', 'flag' => 'sri-lanka.svg', 'region' => 'South Asia'],
            ['name' => 'Singapore', 'code' => 'SG', 'phone_code' => '+65', 'flag' => 'singapore.svg', 'region' => 'Southeast Asia'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'phone_code' => '+852', 'flag' => 'hong-kong.svg', 'region' => 'East Asia'],
            ['name' => 'Turkey', 'code' => 'TR', 'phone_code' => '+90', 'flag' => 'turkey.svg', 'region' => 'Middle East'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'phone_code' => '+966', 'flag' => 'saudi-arabia.svg', 'region' => 'Middle East'],
            ['name' => 'Malaysia', 'code' => 'MY', 'phone_code' => '+60', 'flag' => 'malaysia.svg', 'region' => 'Southeast Asia'],
            ['name' => 'Indonesia', 'code' => 'ID', 'phone_code' => '+62', 'flag' => 'indonesia.svg', 'region' => 'Southeast Asia'],
            ['name' => 'Vietnam', 'code' => 'VN', 'phone_code' => '+84', 'flag' => 'vietnam.svg', 'region' => 'Southeast Asia'],
            ['name' => 'Thailand', 'code' => 'TH', 'phone_code' => '+66', 'flag' => 'thailand.svg', 'region' => 'Southeast Asia'],
            ['name' => 'South Korea', 'code' => 'KR', 'phone_code' => '+82', 'flag' => 'south-korea.svg', 'region' => 'East Asia'],
            ['name' => 'Japan', 'code' => 'JP', 'phone_code' => '+81', 'flag' => 'japan.svg', 'region' => 'East Asia'],
            ['name' => 'Germany', 'code' => 'DE', 'phone_code' => '+49', 'flag' => 'germany.svg', 'region' => 'Europe'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'phone_code' => '+44', 'flag' => 'uk.svg', 'region' => 'Europe'],
            ['name' => 'United States', 'code' => 'US', 'phone_code' => '+1', 'flag' => 'usa.svg', 'region' => 'North America'],
            ['name' => 'Egypt', 'code' => 'EG', 'phone_code' => '+20', 'flag' => 'egypt.svg', 'region' => 'Africa'],
        ];

        foreach ($countries as $country) {
            $country['status'] = 'active';
            $country['created_at'] = date('Y-m-d H:i:s');
            $country['updated_at'] = date('Y-m-d H:i:s');
            $this->db->table('countries')->insert($country);
        }
    }

    private function seedCategories()
    {
        $categories = [
            ['name' => 'Building & Construction', 'slug' => 'building-construction', 'description' => 'Building materials, construction equipment, and supplies'],
            ['name' => 'Agriculture & Food', 'slug' => 'agriculture-food', 'description' => 'Agricultural products, food processing, and farming equipment'],
            ['name' => 'Textiles & Apparel', 'slug' => 'textiles-apparel', 'description' => 'Fabrics, garments, and textile machinery'],
            ['name' => 'Electronics & Electrical', 'slug' => 'electronics-electrical', 'description' => 'Electronic components, electrical equipment, and appliances'],
            ['name' => 'Machinery & Equipment', 'slug' => 'machinery-equipment', 'description' => 'Industrial machinery, tools, and equipment'],
            ['name' => 'Chemicals & Plastics', 'slug' => 'chemicals-plastics', 'description' => 'Chemical products, plastics, and raw materials'],
            ['name' => 'Metals & Minerals', 'slug' => 'metals-minerals', 'description' => 'Metal products, mining, and mineral resources'],
            ['name' => 'Automotive & Transportation', 'slug' => 'automotive-transportation', 'description' => 'Vehicles, auto parts, and transportation equipment'],
            ['name' => 'Health & Medical', 'slug' => 'health-medical', 'description' => 'Medical equipment, pharmaceuticals, and healthcare products'],
            ['name' => 'Home & Garden', 'slug' => 'home-garden', 'description' => 'Furniture, home decor, and garden products'],
            ['name' => 'Sports & Entertainment', 'slug' => 'sports-entertainment', 'description' => 'Sports equipment, toys, and entertainment products'],
            ['name' => 'Packaging & Printing', 'slug' => 'packaging-printing', 'description' => 'Packaging materials, printing services, and supplies'],
        ];

        foreach ($categories as $category) {
            $category['status'] = 'active';
            $category['created_at'] = date('Y-m-d H:i:s');
            $category['updated_at'] = date('Y-m-d H:i:s');
            $this->db->table('categories')->insert($category);
        }
    }

    private function seedSuppliers()
    {
        $suppliers = [
            [
                'company_name' => 'Global Steel Industries',
                'slug' => 'global-steel-industries',
                'category_id' => 7,
                'country_id' => 1,
                'description' => 'Leading manufacturer and exporter of high-quality steel products including structural steel, steel plates, and steel pipes.',
                'business_type' => 'Manufacturer',
                'main_products' => 'Steel Plates, Steel Pipes, Structural Steel, Metal Sheets',
                'year_established' => 2005,
                'employees' => '100-500',
                'annual_revenue' => '$10M - $50M',
                'address' => 'Industrial Area 2',
                'city' => 'Dubai',
                'phone' => '+971-4-1234567',
                'email' => 'info@globalsteel.com',
                'website' => 'www.globalsteel.com',
                'membership_type' => 'platinum',
                'is_verified' => 1,
                'is_featured' => 1,
                'status' => 'approved',
            ],
            [
                'company_name' => 'BuildTech Materials LLC',
                'slug' => 'buildtech-materials',
                'category_id' => 1,
                'country_id' => 1,
                'description' => 'Premium supplier of construction materials including cement, tiles, and building supplies.',
                'business_type' => 'Trading Company',
                'main_products' => 'Cement, Tiles, Bricks, Construction Tools',
                'year_established' => 2010,
                'employees' => '50-100',
                'annual_revenue' => '$5M - $10M',
                'address' => 'Jebel Ali Free Zone',
                'city' => 'Dubai',
                'phone' => '+971-4-2345678',
                'email' => 'sales@buildtech.com',
                'website' => 'www.buildtech.com',
                'membership_type' => 'gold',
                'is_verified' => 1,
                'is_featured' => 1,
                'status' => 'approved',
            ],
            [
                'company_name' => 'Textile Hub Pakistan',
                'slug' => 'textile-hub-pakistan',
                'category_id' => 3,
                'country_id' => 2,
                'description' => 'Premier textile manufacturer specializing in cotton fabrics, denim, and garment exports.',
                'business_type' => 'Manufacturer/Exporter',
                'main_products' => 'Cotton Fabric, Denim, Ready-made Garments, Home Textiles',
                'year_established' => 1998,
                'employees' => '500-1000',
                'annual_revenue' => '$20M - $50M',
                'address' => 'Textile City',
                'city' => 'Faisalabad',
                'phone' => '+92-41-1234567',
                'email' => 'export@textilehub.pk',
                'website' => 'www.textilehub.pk',
                'membership_type' => 'platinum',
                'is_verified' => 1,
                'is_featured' => 1,
                'status' => 'approved',
            ],
            [
                'company_name' => 'AgriGold Exports',
                'slug' => 'agrigold-exports',
                'category_id' => 2,
                'country_id' => 3,
                'description' => 'Leading exporter of agricultural products including rice, spices, and organic foods.',
                'business_type' => 'Exporter',
                'main_products' => 'Basmati Rice, Spices, Organic Foods, Pulses',
                'year_established' => 2008,
                'employees' => '100-200',
                'annual_revenue' => '$10M - $25M',
                'address' => 'Agricultural Zone',
                'city' => 'Mumbai',
                'phone' => '+91-22-12345678',
                'email' => 'sales@agrigold.in',
                'website' => 'www.agrigold.in',
                'membership_type' => 'gold',
                'is_verified' => 1,
                'is_featured' => 0,
                'status' => 'approved',
            ],
            [
                'company_name' => 'TechElectro China',
                'slug' => 'techelectro-china',
                'category_id' => 4,
                'country_id' => 4,
                'description' => 'Major manufacturer of electronic components, LED lighting, and consumer electronics.',
                'business_type' => 'Manufacturer',
                'main_products' => 'LED Lights, Electronic Components, Consumer Electronics, Cables',
                'year_established' => 2000,
                'employees' => '1000+',
                'annual_revenue' => '$100M+',
                'address' => 'Electronics Industrial Park',
                'city' => 'Shenzhen',
                'phone' => '+86-755-12345678',
                'email' => 'info@techelectro.cn',
                'website' => 'www.techelectro.cn',
                'membership_type' => 'business',
                'is_verified' => 1,
                'is_featured' => 1,
                'status' => 'approved',
            ],
            [
                'company_name' => 'Machinery World Co.',
                'slug' => 'machinery-world',
                'category_id' => 5,
                'country_id' => 4,
                'description' => 'Supplier of industrial machinery, CNC machines, and manufacturing equipment.',
                'business_type' => 'Manufacturer/Exporter',
                'main_products' => 'CNC Machines, Industrial Robots, Packaging Machines, Factory Equipment',
                'year_established' => 1995,
                'employees' => '500-1000',
                'annual_revenue' => '$50M - $100M',
                'address' => 'Heavy Industry Zone',
                'city' => 'Guangzhou',
                'phone' => '+86-20-87654321',
                'email' => 'sales@machineryworld.cn',
                'website' => 'www.machineryworld.cn',
                'membership_type' => 'platinum',
                'is_verified' => 1,
                'is_featured' => 1,
                'status' => 'approved',
            ],
            [
                'company_name' => 'ChemPlast Industries',
                'slug' => 'chemplast-industries',
                'category_id' => 6,
                'country_id' => 10,
                'description' => 'Manufacturer and supplier of industrial chemicals, plastics, and petrochemical products.',
                'business_type' => 'Manufacturer',
                'main_products' => 'Industrial Chemicals, Plastic Resins, Petrochemicals, Polymers',
                'year_established' => 2003,
                'employees' => '200-500',
                'annual_revenue' => '$25M - $50M',
                'address' => 'Industrial City',
                'city' => 'Jubail',
                'phone' => '+966-13-1234567',
                'email' => 'info@chemplast.sa',
                'website' => 'www.chemplast.sa',
                'membership_type' => 'gold',
                'is_verified' => 1,
                'is_featured' => 0,
                'status' => 'approved',
            ],
            [
                'company_name' => 'AutoParts Express',
                'slug' => 'autoparts-express',
                'category_id' => 8,
                'country_id' => 9,
                'description' => 'Leading supplier of automotive parts, accessories, and vehicle components.',
                'business_type' => 'Trading Company',
                'main_products' => 'Auto Parts, Car Accessories, Engine Components, Vehicle Electronics',
                'year_established' => 2007,
                'employees' => '100-200',
                'annual_revenue' => '$15M - $30M',
                'address' => 'Automotive Industrial Zone',
                'city' => 'Istanbul',
                'phone' => '+90-212-1234567',
                'email' => 'sales@autopartsexpress.tr',
                'website' => 'www.autopartsexpress.tr',
                'membership_type' => 'gold',
                'is_verified' => 1,
                'is_featured' => 0,
                'status' => 'approved',
            ],
            [
                'company_name' => 'MediCare Supplies',
                'slug' => 'medicare-supplies',
                'category_id' => 9,
                'country_id' => 17,
                'description' => 'Premium supplier of medical equipment, hospital supplies, and healthcare products.',
                'business_type' => 'Distributor',
                'main_products' => 'Medical Equipment, Hospital Furniture, Surgical Instruments, Diagnostic Devices',
                'year_established' => 2001,
                'employees' => '50-100',
                'annual_revenue' => '$10M - $20M',
                'address' => 'Medical District',
                'city' => 'Berlin',
                'phone' => '+49-30-12345678',
                'email' => 'info@medicaresupplies.de',
                'website' => 'www.medicaresupplies.de',
                'membership_type' => 'platinum',
                'is_verified' => 1,
                'is_featured' => 1,
                'status' => 'approved',
            ],
            [
                'company_name' => 'HomeStyle Furniture',
                'slug' => 'homestyle-furniture',
                'category_id' => 10,
                'country_id' => 13,
                'description' => 'Manufacturer of premium furniture, home decor items, and interior accessories.',
                'business_type' => 'Manufacturer',
                'main_products' => 'Living Room Furniture, Bedroom Sets, Office Furniture, Outdoor Furniture',
                'year_established' => 2010,
                'employees' => '200-500',
                'annual_revenue' => '$20M - $40M',
                'address' => 'Furniture Industrial Park',
                'city' => 'Ho Chi Minh City',
                'phone' => '+84-28-12345678',
                'email' => 'export@homestylefurniture.vn',
                'website' => 'www.homestylefurniture.vn',
                'membership_type' => 'gold',
                'is_verified' => 1,
                'is_featured' => 0,
                'status' => 'approved',
            ],
        ];

        foreach ($suppliers as $supplier) {
            $supplier['created_at'] = date('Y-m-d H:i:s');
            $supplier['updated_at'] = date('Y-m-d H:i:s');
            $this->db->table('suppliers')->insert($supplier);
        }
    }

    private function seedProducts()
    {
        $products = [
            [
                'supplier_id' => 1,
                'category_id' => 7,
                'name' => 'Hot Rolled Steel Plates',
                'slug' => 'hot-rolled-steel-plates',
                'description' => 'High-quality hot rolled steel plates suitable for construction, shipbuilding, and industrial applications.',
                'specifications' => 'Thickness: 6-150mm, Width: 1000-4000mm, Length: 3000-18000mm, Grade: A36, SS400, Q235B',
                'min_order_quantity' => 20,
                'min_order_unit' => 'Metric Tons',
                'price_range' => '$500 - $800/MT',
                'supply_ability' => '10000 Metric Tons per month',
                'delivery_time' => '15-30 days',
                'packaging' => 'Standard export packaging with steel straps',
                'port' => 'Jebel Ali Port',
                'payment_terms' => 'T/T, L/C',
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'supplier_id' => 1,
                'category_id' => 7,
                'name' => 'Galvanized Steel Pipes',
                'slug' => 'galvanized-steel-pipes',
                'description' => 'Galvanized steel pipes for plumbing, construction, and structural applications.',
                'specifications' => 'Diameter: 1/2" - 12", Wall Thickness: 1.5-10mm, Length: 6m standard',
                'min_order_quantity' => 5,
                'min_order_unit' => 'Metric Tons',
                'price_range' => '$600 - $900/MT',
                'supply_ability' => '5000 Metric Tons per month',
                'delivery_time' => '7-15 days',
                'packaging' => 'Bundled with steel straps',
                'port' => 'Jebel Ali Port',
                'payment_terms' => 'T/T, L/C',
                'is_featured' => 0,
                'status' => 'active',
            ],
            [
                'supplier_id' => 2,
                'category_id' => 1,
                'name' => 'Portland Cement Grade 53',
                'slug' => 'portland-cement-grade-53',
                'description' => 'High-strength Portland cement for construction projects requiring superior strength.',
                'specifications' => 'Grade: 53, Packing: 50kg bags, Compliance: ASTM C150',
                'min_order_quantity' => 500,
                'min_order_unit' => 'Bags',
                'price_range' => '$5 - $8/Bag',
                'supply_ability' => '100000 Bags per month',
                'delivery_time' => '5-10 days',
                'packaging' => '50kg PP bags on pallets',
                'port' => 'Dubai Port',
                'payment_terms' => 'T/T, Cash',
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'supplier_id' => 3,
                'category_id' => 3,
                'name' => '100% Cotton Fabric',
                'slug' => '100-cotton-fabric',
                'description' => 'Premium quality 100% cotton fabric for garment manufacturing.',
                'specifications' => 'Width: 58-60 inches, Weight: 120-180 GSM, Color: Various',
                'min_order_quantity' => 5000,
                'min_order_unit' => 'Meters',
                'price_range' => '$1.5 - $3/Meter',
                'supply_ability' => '500000 Meters per month',
                'delivery_time' => '20-30 days',
                'packaging' => 'Roll packing with plastic wrap',
                'port' => 'Karachi Port',
                'payment_terms' => 'T/T, L/C at Sight',
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'supplier_id' => 4,
                'category_id' => 2,
                'name' => 'Premium Basmati Rice',
                'slug' => 'premium-basmati-rice',
                'description' => 'Authentic long-grain Basmati rice with rich aroma and taste.',
                'specifications' => 'Grain Length: 8mm+, Moisture: 12% max, Purity: 99%',
                'min_order_quantity' => 25,
                'min_order_unit' => 'Metric Tons',
                'price_range' => '$800 - $1200/MT',
                'supply_ability' => '1000 Metric Tons per month',
                'delivery_time' => '15-25 days',
                'packaging' => '25kg/50kg PP bags or as per buyer requirement',
                'port' => 'Mumbai Port',
                'payment_terms' => 'L/C, T/T 30% advance',
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'supplier_id' => 5,
                'category_id' => 4,
                'name' => 'LED Panel Lights',
                'slug' => 'led-panel-lights',
                'description' => 'Energy-efficient LED panel lights for commercial and residential use.',
                'specifications' => 'Power: 18W-72W, Size: 600x600mm, Color Temp: 3000K-6500K',
                'min_order_quantity' => 500,
                'min_order_unit' => 'Pieces',
                'price_range' => '$8 - $25/Piece',
                'supply_ability' => '100000 Pieces per month',
                'delivery_time' => '10-20 days',
                'packaging' => 'Individual box with foam protection',
                'port' => 'Shenzhen Port',
                'payment_terms' => 'T/T, Western Union',
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'supplier_id' => 6,
                'category_id' => 5,
                'name' => 'CNC Milling Machine',
                'slug' => 'cnc-milling-machine',
                'description' => 'High-precision CNC milling machine for metal fabrication.',
                'specifications' => 'Working Size: 1000x500x500mm, Spindle Speed: 8000RPM, Power: 5.5KW',
                'min_order_quantity' => 1,
                'min_order_unit' => 'Set',
                'price_range' => '$15000 - $25000/Set',
                'supply_ability' => '50 Sets per month',
                'delivery_time' => '30-45 days',
                'packaging' => 'Wooden crate with foam protection',
                'port' => 'Guangzhou Port',
                'payment_terms' => 'T/T 30% deposit, 70% before shipment',
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'supplier_id' => 9,
                'category_id' => 9,
                'name' => 'Hospital Bed Electric',
                'slug' => 'hospital-bed-electric',
                'description' => 'Electric hospital bed with adjustable positions and side rails.',
                'specifications' => 'Size: 2000x900mm, Weight Capacity: 250kg, Functions: 3-Position Electric',
                'min_order_quantity' => 10,
                'min_order_unit' => 'Pieces',
                'price_range' => '$800 - $1500/Piece',
                'supply_ability' => '500 Pieces per month',
                'delivery_time' => '20-30 days',
                'packaging' => 'Carton with wooden pallet',
                'port' => 'Hamburg Port',
                'payment_terms' => 'T/T, L/C',
                'is_featured' => 0,
                'status' => 'active',
            ],
        ];

        foreach ($products as $product) {
            $product['created_at'] = date('Y-m-d H:i:s');
            $product['updated_at'] = date('Y-m-d H:i:s');
            $this->db->table('products')->insert($product);
        }
    }

    private function seedBuyerInquiries()
    {
        $inquiries = [
            [
                'category_id' => 7,
                'country_id' => 19,
                'title' => 'Looking for Steel Plate Suppliers',
                'description' => 'We are looking for reliable steel plate suppliers for our construction projects. Need regular supply for ongoing projects.',
                'product_name' => 'Hot Rolled Steel Plates',
                'quantity' => '500',
                'unit' => 'Metric Tons',
                'target_price' => '$550/MT',
                'buyer_name' => 'John Smith',
                'buyer_email' => 'john.smith@construction.com',
                'buyer_phone' => '+1-555-1234567',
                'buyer_company' => 'Smith Construction Inc.',
                'shipping_terms' => 'CIF',
                'payment_terms' => 'L/C at Sight',
                'destination_port' => 'Los Angeles Port',
                'validity_date' => date('Y-m-d', strtotime('+30 days')),
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'category_id' => 3,
                'country_id' => 18,
                'title' => 'Cotton Fabric for Garment Factory',
                'description' => 'Established garment manufacturer seeking quality cotton fabric suppliers for our UK factory.',
                'product_name' => 'Cotton Fabric 100%',
                'quantity' => '50000',
                'unit' => 'Meters',
                'target_price' => '$2/Meter',
                'buyer_name' => 'Sarah Williams',
                'buyer_email' => 'sarah@ukgarments.co.uk',
                'buyer_phone' => '+44-20-12345678',
                'buyer_company' => 'UK Garments Ltd.',
                'shipping_terms' => 'FOB',
                'payment_terms' => 'T/T 30% advance',
                'destination_port' => 'London Port',
                'validity_date' => date('Y-m-d', strtotime('+45 days')),
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'category_id' => 2,
                'country_id' => 1,
                'title' => 'Bulk Rice Import Requirement',
                'description' => 'Looking for Basmati and long-grain rice suppliers for distribution in the Middle East.',
                'product_name' => 'Basmati Rice Premium',
                'quantity' => '200',
                'unit' => 'Metric Tons',
                'target_price' => '$900/MT',
                'buyer_name' => 'Ahmed Hassan',
                'buyer_email' => 'ahmed@foodimports.ae',
                'buyer_phone' => '+971-50-1234567',
                'buyer_company' => 'Gulf Food Imports LLC',
                'shipping_terms' => 'CIF',
                'payment_terms' => 'L/C',
                'destination_port' => 'Jebel Ali Port',
                'validity_date' => date('Y-m-d', strtotime('+60 days')),
                'is_featured' => 0,
                'status' => 'active',
            ],
            [
                'category_id' => 4,
                'country_id' => 17,
                'title' => 'LED Lighting Products Needed',
                'description' => 'Seeking LED lighting manufacturers for commercial lighting projects in Germany.',
                'product_name' => 'LED Panel Lights & Bulbs',
                'quantity' => '10000',
                'unit' => 'Pieces',
                'target_price' => '$12/Piece',
                'buyer_name' => 'Hans Mueller',
                'buyer_email' => 'hans@germanlighting.de',
                'buyer_phone' => '+49-89-12345678',
                'buyer_company' => 'German Lighting Solutions GmbH',
                'shipping_terms' => 'DDP',
                'payment_terms' => 'T/T 50/50',
                'destination_port' => 'Hamburg',
                'validity_date' => date('Y-m-d', strtotime('+30 days')),
                'is_featured' => 1,
                'status' => 'active',
            ],
            [
                'category_id' => 5,
                'country_id' => 3,
                'title' => 'Industrial Machinery for Manufacturing',
                'description' => 'Looking for CNC machines and industrial equipment for new manufacturing facility.',
                'product_name' => 'CNC Machines',
                'quantity' => '5',
                'unit' => 'Sets',
                'target_price' => '$20000/Set',
                'buyer_name' => 'Rajesh Kumar',
                'buyer_email' => 'rajesh@indiamanufacturing.in',
                'buyer_phone' => '+91-98-12345678',
                'buyer_company' => 'India Manufacturing Pvt Ltd',
                'shipping_terms' => 'CIF',
                'payment_terms' => 'L/C 90 days',
                'destination_port' => 'Mumbai Port',
                'validity_date' => date('Y-m-d', strtotime('+45 days')),
                'is_featured' => 0,
                'status' => 'active',
            ],
            [
                'category_id' => 9,
                'country_id' => 20,
                'title' => 'Medical Equipment for New Hospital',
                'description' => 'New hospital project requiring complete medical equipment and furniture.',
                'product_name' => 'Hospital Beds & Medical Equipment',
                'quantity' => '100',
                'unit' => 'Sets',
                'target_price' => 'Negotiable',
                'buyer_name' => 'Dr. Mohamed Ali',
                'buyer_email' => 'mohamed@egypthospital.eg',
                'buyer_phone' => '+20-2-12345678',
                'buyer_company' => 'Egypt Healthcare Group',
                'shipping_terms' => 'CIF',
                'payment_terms' => 'L/C',
                'destination_port' => 'Alexandria Port',
                'validity_date' => date('Y-m-d', strtotime('+90 days')),
                'is_featured' => 1,
                'status' => 'active',
            ],
        ];

        foreach ($inquiries as $inquiry) {
            $inquiry['created_at'] = date('Y-m-d H:i:s');
            $inquiry['updated_at'] = date('Y-m-d H:i:s');
            $this->db->table('buyer_inquiries')->insert($inquiry);
        }
    }
}
