<?php

namespace App\Models;

/**
 * Country reference data, backed by app/Data/countries.php (a plain PHP
 * array file regenerated by `php spark countries:sync`) instead of a DB
 * table. See that command's docblock and .claude/DECISIONS.md for why:
 * no FK constraints reference countries.id, only one SQL join anywhere
 * touched the old table, and there was never an admin UI to manage rows
 * -- an in-memory array covers every real usage, and PHP's opcache caches
 * the compiled array across requests for free, unlike re-parsing a raw
 * .json file on every load.
 *
 * Deliberately NOT a CodeIgniter Model (no DB query builder available over
 * a static array) but keeps the same public method names used throughout
 * the app (find, findAll, getActiveCountries, getCountryByCode) so no
 * controller call site needed to change.
 */
class CountryModel
{
    private const DATA_PATH = APPPATH . 'Data/countries.php';

    /** @var array<int,array<string,mixed>>|null */
    private static ?array $rows = null;

    private function rows(): array
    {
        if (self::$rows === null) {
            self::$rows = is_file(self::DATA_PATH) ? require self::DATA_PATH : [];
        }
        return self::$rows;
    }

    public function find($id)
    {
        return $this->rows()[(int) $id] ?? null;
    }

    public function findAll(): array
    {
        return $this->rows();
    }

    public function getActiveCountries(): array
    {
        $active = array_filter($this->rows(), static fn ($c) => $c['status'] === 'active');
        usort($active, static fn ($a, $b) => strcmp($a['name'], $b['name']));
        return array_values($active);
    }

    public function getCountryByCode($code)
    {
        $code = strtoupper((string) $code);
        foreach ($this->rows() as $row) {
            if ($row['code'] === $code) {
                return $row;
            }
        }
        return null;
    }

    public function getCountriesByRegion($region): array
    {
        $matches = array_filter(
            $this->rows(),
            static fn ($c) => $c['region'] === $region && $c['status'] === 'active'
        );
        usort($matches, static fn ($a, $b) => strcmp($a['name'], $b['name']));
        return array_values($matches);
    }

    /**
     * Replaces the one raw `whereIn('code', $codes)->findAll()` query-builder
     * chain the old DB-backed model supported (used by
     * UserModel::getLeads() for region filtering) -- that chain doesn't
     * exist over a plain array, so callers get a named method instead.
     */
    public function getCountriesByCodes(array $codes): array
    {
        $codes = array_map('strtoupper', $codes);
        return array_values(array_filter(
            $this->rows(),
            static fn ($c) => in_array($c['code'], $codes, true)
        ));
    }
}
